# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-29 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_responce', models.TextField(blank=True)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_call', to='account.CustomUser', unique=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Synopsis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.TextField()),
                ('phone_number', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('history_description', models.TextField()),
                ('diagnosis', models.TextField(blank=True)),
                ('sick_docs', models.TextField(blank=True)),
                ('sick_description', models.TextField(blank=True)),
                ('healing_description', models.TextField(blank=True)),
                ('how_to_know', models.TextField(blank=True)),
                ('how_recovery', models.TextField(blank=True)),
                ('recovery_information', models.TextField(blank=True)),
                ('recovery_docs', models.TextField(blank=True)),
                ('decision_description', models.TextField(blank=True)),
                ('survey_date', models.TextField(blank=True)),
                ('producer', models.TextField(blank=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_synopsis', to='account.CustomUser')),
            ],
        ),
    ]
