# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 11:30
from __future__ import unicode_literals

from django.db import migrations


def change_hierarchies(apps, schema_editor):
    Hierarchy = apps.get_model("hierarchy", "Hierarchy")

    Hierarchy.objects.filter(level=5).update(level=60)
    Hierarchy.objects.filter(level=6).update(level=70)
    Hierarchy.objects.filter(level=7).update(level=80)

    Hierarchy.objects.get_or_create(level=50, title="Главный епископ")


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0002_auto_20170517_1021'),
    ]

    operations = [
        migrations.RunPython(change_hierarchies, lambda a, b: 0)
    ]
