# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-03 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_country_phone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
    ]
