# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('location', '0005_auto_20160603_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, default='', max_length=5),
            preserve_default=False,
        ),
    ]
