# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigation',
            options={'ordering': ('id',),
                     'verbose_name_plural': '\u041d\u0430\u0432\u0438\u0433\u0430\u0446\u0438\u044f'},
        ),
        migrations.AlterField(
            model_name='columntype',
            name='ordering_title',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='columntype',
            name='verbose_title',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
