# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 12:58
from __future__ import unicode_literals

from django.db import migrations


def create_summit_columns(apps, schema_editor):
    Category = apps.get_model("navigation", "Category")
    ColumnType = apps.get_model("navigation", "ColumnType")

    category, _ = Category.objects.get_or_create(title='summit')
    columns = []
    a = [
        {'title': 'full_name', 'verb': 'ФИО', 'order': 'last_name'},

        {'title': 'responsible', 'verb': 'Ответственный', 'order': 'responsible'},
        {'title': 'spiritual_level', 'verb': 'Духовный уровень', 'order': 'spiritual_level'},
        {'title': 'divisions_title', 'verb': 'Отдел церкви', 'order': 'divisions_title'},
        {'title': 'department', 'verb': 'Отдел', 'order': 'department'},
        {'title': 'hierarchy_title', 'verb': 'Иерархия', 'order': 'hierarchy__level'},

        {'title': 'phone_number', 'verb': 'Номер телефона', 'order': 'user__phone_number'},
        {'title': 'email', 'verb': 'Email', 'order': 'user__email'},
        {'title': 'social', 'verb': 'Социальные сети', 'order': 'user__facebook'},

        {'title': 'country', 'verb': 'Страна', 'order': 'country'},
        {'title': 'city', 'verb': 'Населенный пункт', 'order': 'city'},
        {'title': 'region', 'verb': 'Область', 'order': 'user__region'},
        {'title': 'district', 'verb': 'Район', 'order': 'user__district'},
        {'title': 'address', 'verb': 'Адрес', 'order': 'user__address'},

        {'title': 'born_date', 'verb': 'Дата рождения', 'order': 'user__born_date'},
        {'title': 'repentance_date', 'verb': 'Дата Покаяния', 'order': 'user__repentance_date'},

        {'title': 'code', 'verb': 'Код', 'order': 'code'},
        {'title': 'value', 'verb': 'Оплата', 'order': 'value'},
        {'title': 'description', 'verb': 'Примечание', 'order': 'description'},
    ]
    for i, c in enumerate(a, start=1):
        columns.append(ColumnType(
            title=c['title'],
            category=category,
            verbose_title=c['verb'],
            ordering_title=c['order'],
            number=i,
            active=True,
            editable=True))
    ColumnType.objects.bulk_create(columns)


def delete_summit_columns(apps, schema_editor):
    ColumnType = apps.get_model("navigation", "ColumnType")
    ColumnType.objects.filter(category__title='summit').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('navigation', '0006_auto_20170314_1522'),
    ]

    operations = [
        migrations.RunPython(create_summit_columns, delete_summit_columns)
    ]
