# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0006_auto_20170314_1522'),
        ('navigation', '0004_auto_20170214_1849'),
    ]

    operations = [
    ]
