# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0009_auto_20170503_1422'),
        ('navigation', '0007_auto_20170505_1558'),
    ]

    operations = [
    ]
