# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0008_auto_20170516_1529'),
        ('navigation', '0010_merge_20170517_1440'),
    ]

    operations = [
    ]
