# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 15:43
from __future__ import unicode_literals

from django.db import migrations


def update_meeting_columns_ordering(apps, schema_editor):
    Meeting_columns = apps.get_model('navigation', 'ColumnType')

    meeting_phone_number_column = Meeting_columns.objects.filter(category__title='meetings').filter(title='phone_number')
    meeting_phone_number_column.update(ordering_title='home_group__phone_number')


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0014_auto_20170719_1759'),
    ]

    operations = [
        migrations.RunPython(update_meeting_columns_ordering)
    ]
