# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 16:08
from __future__ import unicode_literals

from django.db import migrations


def update_church_reports_columns_ordering(apps, schema_editor):
    ChurchReport_columns = apps.get_model('navigation', 'ColumnType')

    church_report_column = ChurchReport_columns.objects.filter(category__title='church_report').filter(
        title='total_peoples')
    church_report_column.update(ordering_title='count_people')

    church_report_column = ChurchReport_columns.objects.filter(category__title='church_report').filter(
        title='total_new_peoples')
    church_report_column.update(ordering_title='new_people')

    church_report_column = ChurchReport_columns.objects.filter(category__title='church_report').filter(
        title='total_repentance')
    church_report_column.update(ordering_title='count_repentance')

    church_report_column = ChurchReport_columns.objects.filter(category__title='church_report').filter(
        title='total_tithe')
    church_report_column.update(ordering_title='tithe')

    church_report_column = ChurchReport_columns.objects.filter(category__title='church_report').filter(
        title='total_donations')
    church_report_column.update(ordering_title='donations')

    church_report_column = ChurchReport_columns.objects.filter(category__title='church_report').filter(
        title='total_pastor_tithe')
    church_report_column.update(ordering_title='pastor_tithe')


def delete_church_report_dublicate_column(apps, schema_editor):
    ChurchReport_columns = apps.get_model('navigation', 'ColumnType')

    church_report_dublicate_column = ChurchReport_columns.objects.filter(category__title='church_report').filter(
        verbose_title='15% к перечислению')
    church_report_dublicate_column.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0015_auto_20170731_1543'),
    ]

    operations = [
        migrations.RunPython(update_church_reports_columns_ordering),
        migrations.RunPython(delete_church_report_dublicate_column),
    ]
