# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 14:30
from __future__ import unicode_literals

from django.db import migrations


def create_get_church_column(apps, schema_editor):
    UserColumns = apps.get_model("navigation", "ColumnType")
    Category = apps.get_model("navigation", "Category")

    category = Category.objects.get(id=1)

    UserColumns.objects.bulk_create([
        UserColumns(title='get_church', verbose_title='Церковь', ordering_title='',
                    number=17, active=True, editable=True, category_id=category.id)
    ])


def delete_get_church_column(apps, schema_editor):
    UserColumns = apps.get_model("navigation", "ColumnType")
    Category = apps.get_model("navigation", "Category")

    UserColumns.objects.filter(columnType__title='get_church').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0024_auto_20170913_1449'),
    ]

    operations = [
        migrations.RunPython(create_get_church_column, delete_get_church_column)
    ]
