# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 18:35
from __future__ import unicode_literals

from django.db import migrations


def refactoring_deals_fio_editable(apps, schema_editor):
    Deal_summary_columns = apps.get_model('navigation', 'ColumnType')

    full_name_column = Deal_summary_columns.objects.filter(category__title='deal').filter(title='full_name')
    full_name_column.update(editable=False)


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0026_auto_20170914_1655'),
    ]

    operations = [
        migrations.RunPython(refactoring_deals_fio_editable)
    ]
