# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 14:22
from __future__ import unicode_literals

from django.db import migrations


def create_partnership_summary_total_sum_column(apps, schema_editor):
    Partnership_summary_columns = apps.get_model("navigation", "ColumnType")
    Category = apps.get_model("navigation", "Category")

    partnership_summary = Category.objects.get(title='partnership_summary')

    Partnership_summary_columns.objects.bulk_create([
        Partnership_summary_columns(title='total_sum', verbose_title='Общая сумма',
                                    ordering_title='total_sum',
                                    number=11, active=True, editable=True, category_id=partnership_summary.id),
    ])


def delete_partnership_summary_total_sum_column(apps, schema_editor):
    Partnership_summary_columns = apps.get_model("navigation", "ColumnType")

    Partnership_summary_columns.objects.filter(category__title='partnership_summary', title='total_sum').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0034_auto_20171107_1542'),
    ]

    operations = [
        migrations.RunPython(create_partnership_summary_total_sum_column, delete_partnership_summary_total_sum_column),
    ]
