# Generated by Django 2.0.2 on 2018-03-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0036_auto_20171210_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='columnType',
        ),
        migrations.RemoveField(
            model_name='column',
            name='table',
        ),
        migrations.RemoveField(
            model_name='columntype',
            name='category',
        ),
        migrations.DeleteModel(
            name='Navigation',
        ),
        migrations.RemoveField(
            model_name='table',
            name='columnTypes',
        ),
        migrations.RemoveField(
            model_name='table',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.DeleteModel(
            name='ColumnType',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
