# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 13:18
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0003_auto_20160621_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, verbose_name='Number')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_phones',
                                   to='account.CustomUser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Additional Phone Number',
                'verbose_name_plural': 'Additional Phone Numbers',
            },
        ),
        migrations.AlterUniqueTogether(
            name='additionalphonenumber',
            unique_together=set([('user', 'number')]),
        ),
    ]
