# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-21 07:33
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0004_auto_20160922_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'Consultants',
                'verbose_name': 'Consultant',
            },
            bases=('account.customuser',),
        ),
        migrations.AddField(
            model_name='customuser',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='consultees', to='account.CustomUser'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_consultant',
            field=models.BooleanField(default=False, verbose_name='Is consult?'),
        ),
    ]
