# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-24 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0004_auto_20161024_1618'),
        ('account', '0005_customuser_summit_consultants'),
    ]

    operations = [
    ]
