# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-21 08:00
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0005_auto_20161021_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='consultees', to='account.Consultant'),
        ),
    ]
