# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-18 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0010_customuser_summit_consultants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='summit_consultants',
        ),
    ]
