# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20161212_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='search_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Field for search by name'),
        ),
    ]
