# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 10:09
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_merge_20170117_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='extra_phone_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Number'), blank=True, null=True, size=None),
        ),
    ]
