# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 10:10
from __future__ import unicode_literals

from django.db import migrations


def add_extra_phone_numbers(apps, schema_editor):
    User = apps.get_model("account", "CustomUser")

    users = User.objects.filter(additional_phones__isnull=False)
    for user in users:
        phones = filter(lambda number: bool(number),
                        map(lambda n: n.strip().replace('\u200e', ''),
                            user.additional_phones.values_list('number', flat=True)))
        if phones:
            user.extra_phone_numbers = list(phones)
            user.save()


def del_extra_phone_numbers(apps, schema_editor):
    User = apps.get_model("account", "CustomUser")

    User.objects.all().update(extra_phone_numbers=None)


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0015_customuser_extra_phone_numbers'),
    ]

    operations = [
        migrations.RunPython(add_extra_phone_numbers, del_extra_phone_numbers),
    ]
