# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0001_initial'),
        ('account', '0018_auto_20170302_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='departments',
            field=models.ManyToManyField(related_name='userss', to='hierarchy.Department'),
        ),
    ]
