# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 15:44
from __future__ import unicode_literals

from django.db import migrations


def update_departments(apps, schema_editor):
    User = apps.get_model("account", "CustomUser")

    for user in User.objects.all():
        if user.department:
            user.departments.set([user.department])
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_customuser_departments'),
    ]

    operations = [
        migrations.RunPython(update_departments),
    ]
