# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-07 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20170314_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_login',
            field=models.BooleanField(default=False, verbose_name='Can login to site'),
        ),
    ]
