# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20170314_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hierarchy_order',
        ),
    ]
