# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-07 08:30
from __future__ import unicode_literals

from django.db import migrations


def set_can_login(apps, schema_editor):
    CustomUser = apps.get_model("account", "CustomUser")

    CustomUser.objects.filter(last_login__isnull=False).update(can_login=True)


def reset_can_login(apps, schema_editor):
    CustomUser = apps.get_model("account", "CustomUser")

    CustomUser.objects.update(can_login=False)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_customuser_can_login'),
    ]

    operations = [
        migrations.RunPython(set_can_login, reset_can_login),
    ]
