# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_homegroup_active'),
        ('account', '0026_auto_20170606_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cchurch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uusers', to='group.Church', verbose_name='Church'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hhome_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uusers', to='group.HomeGroup', verbose_name='Home group'),
        ),
    ]
