# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 10:30
from __future__ import unicode_literals

from django.db import migrations


def add_extra_phone_numbers(apps, schema_editor):
    User = apps.get_model("account", "CustomUser")

    for user in User.objects.all():
        church = user.churches.first()
        home_group = user.home_groups.first()
        user.cchurch = church if church else None
        user.hhome_group = home_group if home_group else None
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20170613_1029'),
    ]

    operations = [
        migrations.RunPython(add_extra_phone_numbers, lambda a, s: 0),
    ]
