# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20170613_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='born_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Born date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=23, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='search_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Field for search by name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='spiritual_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Renegade'), (1, 'Baby'), (2, 'Junior'), (3, 'Father')], db_index=True, default=1, verbose_name='Spiritual Level'),
        ),
    ]
