# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20170807_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='depth',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
