# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_auto_20170822_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='level',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='depth',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disciples', to='account.CustomUser', verbose_name='Master'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
