# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20170822_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cchurch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uusers', to='group.Church', verbose_name='Church'),
        ),
    ]
