# Generated by Django 2.0.4 on 2018-04-25 08:53

import apps.lesson.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0044_added_sex_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('slug', models.SlugField(editable=False, max_length=255, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=9, verbose_name='Status')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons', verbose_name='Image')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_textlessons', to='account.CustomUser')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='creator_textlessons', to='account.CustomUser')),
            ],
            options={
                'verbose_name': 'Text lesson',
                'verbose_name_plural': 'Text lessons',
                'db_table': 'lesson_text',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='TextLessonLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lesson.TextLesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.CustomUser')),
            ],
            options={
                'db_table': 'lesson_text_like',
            },
        ),
        migrations.CreateModel(
            name='TextLessonView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lesson.TextLesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.CustomUser')),
            ],
            options={
                'db_table': 'lesson_text_view',
            },
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('slug', models.SlugField(editable=False, max_length=255, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=9, verbose_name='Status')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Description')),
                ('url', apps.lesson.validators.YoutubeURLField(max_length=255, verbose_name='youtube url')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_videolessons', to='account.CustomUser')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='creator_videolessons', to='account.CustomUser')),
            ],
            options={
                'verbose_name': 'Video lesson',
                'verbose_name_plural': 'Video lessons',
                'db_table': 'lesson_video',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='VideoLessonLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lesson.VideoLesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.CustomUser')),
            ],
            options={
                'db_table': 'lesson_video_like',
            },
        ),
        migrations.CreateModel(
            name='VideoLessonView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lesson.VideoLesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.CustomUser')),
            ],
            options={
                'db_table': 'lesson_video_view',
            },
        ),
        migrations.AddField(
            model_name='videolesson',
            name='likes',
            field=models.ManyToManyField(related_name='like_video_lessons', through='lesson.VideoLessonLike', to='account.CustomUser', verbose_name='Views'),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='views',
            field=models.ManyToManyField(related_name='view_video_lessons', through='lesson.VideoLessonView', to='account.CustomUser', verbose_name='Views'),
        ),
        migrations.AddField(
            model_name='textlesson',
            name='likes',
            field=models.ManyToManyField(related_name='like_text_lessons', through='lesson.TextLessonLike', to='account.CustomUser', verbose_name='Views'),
        ),
        migrations.AddField(
            model_name='textlesson',
            name='views',
            field=models.ManyToManyField(related_name='view_text_lessons', through='lesson.TextLessonView', to='account.CustomUser', verbose_name='Views'),
        ),
    ]
