# Generated by Django 2.0.5 on 2018-05-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_added_sex_field'),
        ('lesson', '0002_auto_20180503_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='textlesson',
            name='authors',
            field=models.ManyToManyField(related_name='authors_textlessons', to='account.CustomUser'),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='authors',
            field=models.ManyToManyField(related_name='authors_videolessons', to='account.CustomUser'),
        ),
    ]
