# Generated by Django 2.0.5 on 2018-05-04 08:50

from django.db import migrations


def set_authors(apps, schema_editor):
    TextLesson = apps.get_model("lesson", "TextLesson")
    VideoLesson = apps.get_model("lesson", "VideoLesson")

    for l in TextLesson.objects.all():
        if l.author:
            l.authors.set([l.author.pk])
        else:
            l.authors.clear()

    for l in VideoLesson.objects.all():
        if l.author:
            l.authors.set([l.author.pk])
        else:
            l.authors.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_auto_20180504_0847'),
    ]

    operations = [
        migrations.RunPython(set_authors),
    ]
