# Generated by Django 2.0.5 on 2018-05-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_auto_20180504_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textlesson',
            name='author',
        ),
        migrations.RemoveField(
            model_name='videolesson',
            name='author',
        ),
    ]
