# Generated by Django 2.0.5 on 2018-05-23 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_auto_20180517_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextLessonImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='lessons', verbose_name='Image')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Display order')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lesson.TextLesson')),
            ],
            options={
                'ordering': ('display_order', 'pk'),
            },
        ),
    ]
