# Generated by Django 2.0.5 on 2018-05-23 12:03

from django.db import migrations


def create_images(apps, schema_editor):
    TextLesson = apps.get_model("lesson", "TextLesson")
    TextLessonImage = apps.get_model("lesson", "TextLessonImage")

    for l in TextLesson.objects.all():
        if l.image:
            TextLessonImage.objects.create(url=l.image, lesson=l)


def delete_images(apps, schema_editor):
    TextLessonImage = apps.get_model("lesson", "TextLessonImage")

    TextLessonImage.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('lesson', '0007_textlessonimage'),
    ]

    operations = [
        migrations.RunPython(create_images, delete_images),
    ]
