# Generated by Django 2.0.8 on 2018-09-06 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_migrate_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextLessonVideoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lesson.VideoFile')),
            ],
            options={
                'db_table': 'lesson_text_video',
            },
        ),
        migrations.AlterField(
            model_name='textlesson',
            name='likes',
            field=models.ManyToManyField(related_name='like_text_lessons', through='lesson.TextLessonLike', to='account.CustomUser', verbose_name='Likes'),
        ),
        migrations.AddField(
            model_name='textlessonvideofile',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lesson.TextLesson'),
        ),
        migrations.AddField(
            model_name='textlesson',
            name='video_files',
            field=models.ManyToManyField(related_name='videos_text_lessons', through='lesson.TextLessonVideoFile', to='lesson.VideoFile', verbose_name='Videos'),
        ),
    ]
