# Generated by Django 2.0.7 on 2018-08-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_auth', '0002_lighttoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneconfirmation',
            name='key',
            field=models.CharField(max_length=64, verbose_name='key'),
        ),
        migrations.AlterUniqueTogether(
            name='phoneconfirmation',
            unique_together={('phone_number', 'key')},
        ),
    ]
