image: docker:latest
services:
  - docker:dind

before_script:
    - docker login -u amirr -p $MCI_BUILD_TOKEN $MCI_REGISTRY

stages:
  - build
  - test
  - deploy

build-stage:
  stage: build
  script:
    - docker build -t reg.sobsam.com/vocrm:latest .
    - docker push reg.sobsam.com/vocrm:latest
  only:
    - master

build-prod:
  stage: build
  script:
    - docker build -t reg.sobsam.com/vocrm:$CI_COMMIT_TAG -t reg.sobsam.com/vocrm:stable .
    - docker push reg.sobsam.com/vocrm:$CI_COMMIT_TAG
    - docker push reg.sobsam.com/vocrm:stable
  only:
    - tags

test-stage:
  stage: test
  services:
  - name: docker:dind
  - name: postgres:10
    alias: db
  - name: redis:latest
    alias: redis
  script:
    - docker pull reg.sobsam.com/vocrm:latest
    - docker run -d --name db reg.sobsam.com/postgres:10
    - docker run -d --name redis redis:latest
    - docker ps && sleep 10
    - docker run --rm -e POSTGRES_USER='postgres' -e POSTGRES_PASSWORD='' -e POSTGRES_DB='test_crm_db' -e DJANGO_SETTINGS_MODULE='edem.settings.test' -e POSTGRES_HOST='db' --name pytest --link db --link redis reg.sobsam.com/vocrm:latest python manage.py test
  only:
    - master

test-prod:
  stage: test
  services:
  - name: docker:dind
  - name: postgres:10
    alias: db
  - name: redis:latest
    alias: redis
  script:
    - docker pull reg.sobsam.com/vocrm:$CI_COMMIT_TAG
    - docker run -d --name db reg.sobsam.com/postgres:10
    - docker run -d --name redis redis:latest
    - docker ps && sleep 10
    - docker run --rm -e POSTGRES_USER='postgres' -e POSTGRES_PASSWORD='' -e POSTGRES_DB='test_crm_db' -e DJANGO_SETTINGS_MODULE='edem.settings.test' -e POSTGRES_HOST='db' --name pytest --link db --link redis reg.sobsam.com/vocrm:$CI_COMMIT_TAG python manage.py test
  only:
    - tags

deploy-stage:
  stage: deploy
  image: python:3.6
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh $STAGE_USER@$STAGE_HOST "/home/vocrm/sites/vocrm/update.sh"
  only:
    - master

deploy-prod:
  stage: deploy
  image: python:3.6
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh $DB_USER@$DB_HOST "/home/db/backup.sh"
    - ssh $PROD_USER@$PROD_HOST "VOCRM_TAG=$CI_COMMIT_TAG /home/vocrm/sites/vocrm/update.sh"
  only:
    - tags
  when: manual
