version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}
  redis_data_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=crm_user
      - POSTGRES_DB=crm_db
      - POSTGRES_PASSWORD=crm_pass

  redis:
    image: redis:latest
    volumes:
      - redis_data_dev:/data

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_USER=crm_user
      - POSTGRES_DB=crm_db
      - POSTGRES_PASSWORD=crm_pass
      - USE_DOCKER=yes
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:7000:8000"
    links:
      - postgres
      - redis

  pycharm:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_USER=crm_user
      - POSTGRES_DB=crm_db
      - POSTGRES_PASSWORD=crm_pass
      - USE_DOCKER=yes
    volumes:
      - .:/app
    links:
      - postgres
      - redis
