version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}
  redis_data_dev: {}
  es_data_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=crm_user
      - POSTGRES_DB=crm_db
      - POSTGRES_PASSWORD=crm_pass
    ports:
      - "4321:5432"

  redis:
    image: redis:latest
    volumes:
      - redis_data_dev:/data

  es:
    image: elasticsearch:latest
    volumes:
      - es_data_dev:/data
    ports:
      - "9200:9200"

  kibana:
    image: kibana:latest
    environment:
      - ELASTICSEARCH_URL=http://es:9200
    ports:
      - "5601:5601"

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_USER=crm_user
      - POSTGRES_DB=crm_db
      - POSTGRES_PASSWORD=crm_pass
      - USE_DOCKER=yes
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:7000:8000"
    links:
      - postgres
      - redis
      - es

  celeryworker:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    environment:
      - POSTGRES_USER=crm_user
      - POSTGRES_DB=crm_db
      - POSTGRES_PASSWORD=crm_pass
      - CELERY_BROKER_URL=redis://redis:6379/0
      - USE_DOCKER=yes
      - SECRET_KEY=khkjhdjdjksvgsdklsnakjfhjkzhcjks
      - DJANGO_SETTINGS_MODULE=edem.settings.dev
      - C_FORCE_ROOT=1
    depends_on:
     - postgres
     - redis
    volumes:
      - .:/app
    command: celery -A edem worker -l INFO -c 4

  flower:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    environment:
      - POSTGRES_USER=crm_user
      - POSTGRES_DB=crm_db
      - POSTGRES_PASSWORD=crm_pass
      - CELERY_BROKER_URL=redis://redis:6379/0
      - USE_DOCKER=yes
      - SECRET_KEY=khkjhdjdjksvgsdklsnakjfhjkzhcjks
      - DJANGO_SETTINGS_MODULE=edem.settings.dev
      - C_FORCE_ROOT=1
    depends_on:
     - postgres
     - redis
    ports:
      - "127.0.0.1:5555:5555"
    volumes:
      - .:/app
    command: celery flower

  pycharm:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_USER=crm_user
      - POSTGRES_DB=crm_db
      - POSTGRES_PASSWORD=crm_pass
      - USE_DOCKER=yes
    volumes:
      - .:/app
    links:
      - postgres
      - redis
