version: '3'

services:
  ticket:
    restart: always
    build:
      context: .
      dockerfile: ./compose/scanner/Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - nginx_data:/app/public
    user: flask
    depends_on:
      - postgres
    command: /gunicorn.sh
    env_file: .envf
    environment:
      - VIRTUAL_HOST=ticket.vocrm.net
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - HTTPS_METHOD=redirect
      - CLOSE_SITE=no
      - LETSENCRYPT_HOST=ticket.vocrm.net
      - LETSENCRYPT_EMAIL=pluton@freeday.com.ua
      - DEBUG=true
