# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u041d\u0430\u0432\u0438\u0433\u0430\u0446\u0438\u044f',
            },
        ),
    ]
