# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecord',
            name='action_flag',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Addition'), (2, 'Change'), (3, 'Deletion')], default=2, verbose_name='action flag'),
        ),
        migrations.AlterField(
            model_name='logrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_records', to='account.CustomUser', verbose_name='user'),
        ),
    ]
