# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-29 13:46
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0002_auto_20160429_1646'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('home_count', models.IntegerField(default=0)),
                ('home_value', models.IntegerField(default=0)),
                ('night_count', models.IntegerField(default=0)),
                ('service_count', models.IntegerField(default=0)),
                ('service_coming_count', models.IntegerField(default=0)),
                ('service_repentance_count', models.IntegerField(default=0)),
                ('home_as_leader_count', models.IntegerField(default=0)),
                ('home_as_leader_value', models.IntegerField(default=0)),
                ('night_as_leader_count', models.IntegerField(default=0)),
                ('service_as_leader_count', models.IntegerField(default=0)),
                ('service_as_leader_coming_count', models.IntegerField(default=0)),
                ('service_as_leader_repentance_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_report', to='account.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='WeekReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(default=timezone.now)),
                ('to_date', models.DateField(default=timezone.now)),
                ('home_count', models.IntegerField(default=0)),
                ('home_value', models.IntegerField(default=0)),
                ('night_count', models.IntegerField(default=0)),
                ('service_count', models.IntegerField(default=0)),
                ('service_coming_count', models.IntegerField(default=0)),
                ('service_repentance_count', models.IntegerField(default=0)),
                ('home_as_leader_count', models.IntegerField(default=0)),
                ('home_as_leader_value', models.IntegerField(default=0)),
                ('night_as_leader_count', models.IntegerField(default=0)),
                ('service_as_leader_count', models.IntegerField(default=0)),
                ('service_as_leader_coming_count', models.IntegerField(default=0)),
                ('service_as_leader_repentance_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_reports', to='report.UserReport')),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_reports', to='event.Week')),
            ],
        ),
        migrations.CreateModel(
            name='YearReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('home_count', models.IntegerField(default=0)),
                ('home_value', models.IntegerField(default=0)),
                ('night_count', models.IntegerField(default=0)),
                ('service_count', models.IntegerField(default=0)),
                ('service_coming_count', models.IntegerField(default=0)),
                ('service_repentance_count', models.IntegerField(default=0)),
                ('home_as_leader_count', models.IntegerField(default=0)),
                ('home_as_leader_value', models.IntegerField(default=0)),
                ('night_as_leader_count', models.IntegerField(default=0)),
                ('service_as_leader_count', models.IntegerField(default=0)),
                ('service_as_leader_coming_count', models.IntegerField(default=0)),
                ('service_as_leader_repentance_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_reports', to='report.UserReport')),
            ],
        ),
        migrations.AddField(
            model_name='monthreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month_reports', to='report.UserReport'),
        ),
    ]
