# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-31 09:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20160504_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekreport',
            name='from_date',
            field=models.DateField(default=datetime.date(2016, 5, 31)),
        ),
        migrations.AlterField(
            model_name='weekreport',
            name='to_date',
            field=models.DateField(default=datetime.date(2016, 5, 31)),
        ),
    ]
