# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-14 14:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20160701_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekreport',
            name='from_date',
            field=models.DateField(default=datetime.date(2016, 9, 14)),
        ),
        migrations.AlterField(
            model_name='weekreport',
            name='to_date',
            field=models.DateField(default=datetime.date(2016, 9, 14)),
        ),
    ]
