# Generated by Django 2.0.8 on 2018-10-29 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20181023_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsmanager',
            name='group',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='manage_person', to='group.HomeGroup', verbose_name='Group'),
        ),
    ]
