# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-05 13:14
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20170104_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency_rate',
            field=models.ForeignKey(default=payment.models.get_default_currency, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rate_payments', to='payment.Currency', verbose_name='Rate currency'),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency_sum',
            field=models.ForeignKey(default=payment.models.get_default_currency, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sum_payments', to='payment.Currency', verbose_name='Currency of sum'),
        ),
        migrations.AddField(
            model_name='payment',
            name='effective_sum',
            field=models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=12, null=True, verbose_name='Effective sum'),
        ),
        migrations.AddField(
            model_name='payment',
            name='rate',
            field=models.DecimalField(decimal_places=0, default=Decimal('1'), max_digits=12, verbose_name='Rate'),
        ),
    ]
