# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 16:40
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20170203_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='effective_sum',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=12, null=True, verbose_name='Effective sum'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, verbose_name='Rate'),
        ),
    ]
