# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 07:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def add_hierarchies(apps, schema_editor):
    Hierarchy = apps.get_model("hierarchy", "Hierarchy")

    for hierarchy in settings.HIERARCHIES:
        Hierarchy.objects.get_or_create(**hierarchy)


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_hierarchies, lambda a, b: 0)
    ]
