# Generated by Django 2.0.4 on 2018-04-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0003_auto_20170627_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchy',
            name='code',
            field=models.SlugField(blank=True, verbose_name='Code'),
        ),
    ]
