# Generated by Django 2.0.4 on 2018-04-12 11:31
from django.db import migrations


CODES = {
    14: 'lead',
    12: 'convert',
    1: 'congregation',
    13: 'trainee',
    2: 'leader',
    3: 'centurion',
    4: 'pastor',
    10: 'responsible',
    5: 'bishop',
    11: 'main_bishop',
    8: 'senior_bishop',
    6: 'apostle',
    7: 'archon',
}


def add_hierarchies(apps, schema_editor):
    Hierarchy = apps.get_model("hierarchy", "Hierarchy")

    i = 0
    for hierarchy in Hierarchy.objects.all():
        code = CODES.get(hierarchy.pk, '')
        if not code:
            code = f'code{i}'
            i += 1
        hierarchy.code = code
        hierarchy.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0004_added_code_field_to_hierarchy'),
    ]

    operations = [
        migrations.RunPython(add_hierarchies, lambda a, b: 0)
    ]
