# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-29 09:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0010_auto_20160628_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='date',
            field=models.DateField(default=datetime.date(2016, 6, 29)),
        ),
    ]
