# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-14 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0013_auto_20160914_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ('date_created',)},
        ),
        migrations.AddField(
            model_name='deal',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='partnership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='partnership.Partnership', unique_for_month='date_created'),
        ),
    ]
