# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-31 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('partnership', '0015_auto_20160921_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='need_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Need text'),
        ),
    ]
