# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-01 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('partnership', '0017_partnership_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active?'),
        ),
    ]
