# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-03 10:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('partnership', '0020_remove_partnership_is_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='partnership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals',
                                    to='partnership.Partnership'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
