# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-07 12:16
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('partnership', '0021_auto_20161103_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
