# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0025_auto_20170111_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterField(
            model_name='deal',
            name='currency',
            field=models.ForeignKey(default=payment.models.get_default_currency, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.Currency', verbose_name='Currency'),
        ),
    ]
