# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0026_auto_20170214_1849'),
        ('partnership', '0029_auto_20170328_1510'),
    ]

    operations = [
    ]
