# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0031_auto_20170905_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershiplogs',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_disciples', to='partnership.Partnership'),
        ),
    ]
