# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_auto_20171004_1634'),
        ('partnership', '0034_auto_20171012_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Director'), (1, 'Supervisor'), (2, 'Manager')], verbose_name='Level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_role', to='account.CustomUser')),
            ],
        ),
    ]
