# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 17:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def create_partner_roles(apps, schema_editor):
    Partnership = apps.get_model("partnership", "Partnership")
    PartnerRole = apps.get_model("partnership", "PartnerRole")

    for partner in Partnership.objects.filter(level__lte=settings.PARTNER_LEVELS['manager']):
        PartnerRole.objects.create(user=partner.user, level=partner.level)


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0035_partnerrole'),
    ]

    operations = [
        migrations.RunPython(create_partner_roles),
    ]
