# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0038_set_user_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='partnershiplogs',
            name='responsible',
        ),
    ]
