# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 15:51
from __future__ import unicode_literals

from django.db import migrations


def copy_data(apps, schema_editor):
    PartnerRole = apps.get_model("partnership", "PartnerRole")
    PartnerRoleLog = apps.get_model("partnership", "PartnerRoleLog")
    PartnershipLogs = apps.get_model("partnership", "PartnershipLogs")

    for partner_role in PartnerRole.objects.all():
        for log in PartnershipLogs.objects.filter(partner__in=partner_role.user.partners.all()):
            l = PartnerRoleLog.objects.create(user=log.partner.user, level=log.level, plan=log.plan, log_date=log.log_date)
            l.log_date = log.log_date
            l.save()


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0044_create_partner_role_log_table'),
    ]

    operations = [
        migrations.RunPython(copy_data),
    ]
