# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0045_added_data_to_partner_role_log_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnership',
            name='level',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='partnershiplogs',
            name='level',
        ),
        migrations.RemoveField(
            model_name='partnershiplogs',
            name='plan',
        ),
    ]
