# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0046_del_level_and_plan_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerrolelog',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
    ]
