# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0047_partnerrolelog_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Partner group')),
            ],
        ),
        migrations.AddField(
            model_name='partnership',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='partnership.PartnerGroup'),
        ),
        migrations.AddField(
            model_name='partnershiplogs',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners_logs', to='partnership.PartnerGroup'),
        ),
    ]
