# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 11:41
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_payment_operation'),
        ('account', '0036_customuser_manager'),
        ('group', '0012_auto_20171101_1141'),
        ('partnership', '0052_set_parter_title_eq_UA'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('done', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
                ('date_created', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Donation'), (2, 'Tithe')], default=1, verbose_name='Deal type')),
                ('currency', models.ForeignKey(default=payment.models.get_default_currency, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.Currency', verbose_name='Currency')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='ChurchPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('date', models.DateField(default=datetime.date.today)),
                ('need_text', models.CharField(blank=True, max_length=600, verbose_name='Need text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('title', models.CharField(choices=[('UA', 'UA'), ('EU', 'EU')], default='UA', max_length=255, verbose_name='Partner title')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='group.Church')),
                ('currency', models.ForeignKey(default=payment.models.get_default_currency, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.Currency', verbose_name='Currency')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='church_partners', to='partnership.PartnerGroup', verbose_name='Group')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='church_partner_disciples', to='account.CustomUser', verbose_name='Responsible')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChurchPartnerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('date', models.DateField(default=datetime.date.today)),
                ('need_text', models.CharField(blank=True, max_length=600, verbose_name='Need text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('title', models.CharField(choices=[('UA', 'UA'), ('EU', 'EU')], default='UA', max_length=255, verbose_name='Partner title')),
                ('log_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Log date')),
                ('currency', models.ForeignKey(default=payment.models.get_default_currency, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.Currency', verbose_name='Currency')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='church_partners_logs', to='partnership.PartnerGroup')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='partnership.ChurchPartner', verbose_name='Partner')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='church_partner_disciples_logs', to='account.CustomUser')),
            ],
            options={
                'verbose_name': 'Church Partner Log',
                'verbose_name_plural': 'Church Partner Logs',
                'ordering': ('-log_date',),
            },
        ),
        migrations.AddField(
            model_name='churchdeal',
            name='partnership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='partnership.ChurchPartner'),
        ),
        migrations.AddField(
            model_name='churchdeal',
            name='responsible',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_disciples_deals', to='account.CustomUser', verbose_name='Responsible of partner'),
        ),
    ]
