# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0053_auto_20171101_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnergroup',
            name='type',
            field=models.CharField(choices=[('user', 'User'), ('church', 'Church')], default='user', max_length=255, verbose_name='Type'),
        ),
    ]
