# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-29 13:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.datetime(2016, 4, 29, 13, 46, 3, 275284, tzinfo=utc)),
        ),
    ]
