# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 12:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20160429_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='result_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='from_date',
            field=models.DateField(default=datetime.date(2016, 5, 4)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.datetime(2016, 5, 4, 12, 29, 24, 327611, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='to_date',
            field=models.DateField(default=datetime.date(2016, 5, 4)),
        ),
        migrations.AlterField(
            model_name='week',
            name='from_date',
            field=models.DateField(default=datetime.date(2016, 5, 4)),
        ),
        migrations.AlterField(
            model_name='week',
            name='to_date',
            field=models.DateField(default=datetime.date(2016, 5, 4)),
        ),
        migrations.AlterField(
            model_name='week',
            name='week',
            field=models.IntegerField(default=18, unique=True),
        ),
    ]
