# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-01 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20160601_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.datetime(2016, 6, 1, 13, 54, 55, 646277, tzinfo=utc)),
        ),
    ]
