# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-23 12:20
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20161212_1636'),
        ('event', '0023_auto_20160922_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('total_sum', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total sum')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.CustomUser')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ('owner', '-date'),
            },
        ),
        migrations.CreateModel(
            name='MeetingAttend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False, verbose_name='Attended')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attends', to='event.Meeting', verbose_name='Meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attends', to='account.CustomUser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Meeting attend',
                'verbose_name_plural': 'Meeting attendees',
                'ordering': ('meeting__owner', '-meeting__date'),
            },
        ),
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('code', models.SlugField(max_length=255, unique=True, verbose_name='Code')),
                ('image', models.ImageField(blank=True, upload_to='images/meeting_type/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Meeting type',
                'verbose_name_plural': 'Meeting types',
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.MeetingType', verbose_name='Meeting type'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='visitors',
            field=models.ManyToManyField(related_name='meeting_types', through='event.MeetingAttend', to='account.CustomUser', verbose_name='Visitors'),
        ),
    ]
