# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20170214_1849'),
        ('event', '0025_auto_20161223_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='home_group',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.PROTECT, to='group.HomeGroup', verbose_name='Home Group'),
        ),
    ]
