# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_meeting_home_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='home_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='group.HomeGroup', verbose_name='Home Group'),
        ),
    ]
