# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20170131_1439'),
        ('group', '0004_auto_20170214_1849'),
        ('event', '0027_auto_20170215_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('count_people', models.IntegerField(verbose_name='Count People')),
                ('new_people', models.IntegerField(verbose_name='New People')),
                ('count_repentance', models.IntegerField(verbose_name='Number of Repentance')),
                ('tithe', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tithe')),
                ('donations', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Donations')),
                ('currency_donations', models.CharField(max_length=150, verbose_name='Donations in Currency')),
                ('transfer_payments', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Transfer Payments')),
                ('pastor_tithe', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Pastor Tithe')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='group.Church', verbose_name='Church')),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.CustomUser')),
            ],
            options={
                'ordering': ('date', 'church'),
                'verbose_name': 'Church Report',
                'verbose_name_plural': 'Church Reports',
            },
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('-date', 'owner'), 'verbose_name': 'Meeting', 'verbose_name_plural': 'Meetings'},
        ),
    ]
