# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_auto_20170428_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='home_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.HomeGroup', verbose_name='Home Group'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.MeetingType', verbose_name='Meeting type'),
        ),
    ]
