# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0035_auto_20170725_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchreportpastor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='church_report_pastor', to='account.CustomUser', verbose_name='Church Report Pastor'),
        ),
    ]
