# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0041_auto_20170823_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchreport',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
