# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0043_auto_20171121_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('-id', '-date'), 'verbose_name': 'Meeting', 'verbose_name_plural': 'Meetings'},
        ),
        migrations.AlterModelOptions(
            name='meetingattend',
            options={'ordering': ('meeting__owner', '-meeting__date'), 'verbose_name': 'Meeting attend', 'verbose_name_plural': 'Meeting attendees'},
        ),
        migrations.AlterModelOptions(
            name='meetingtype',
            options={'verbose_name': 'Meeting type', 'verbose_name_plural': 'Meeting types'},
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='count_repentance',
            field=models.IntegerField(default=0, verbose_name='Number of Repentance'),
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='currency',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.Currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='currency_donations',
            field=models.CharField(blank=True, max_length=150, verbose_name='Donations in Currency'),
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='donations',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Donations'),
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='new_people',
            field=models.IntegerField(default=0, verbose_name='New People'),
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='pastor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.CustomUser'),
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'in_progress'), (2, 'submitted'), (3, 'expired')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='tithe',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tithe'),
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='transfer_payments',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=12, verbose_name='Transfer Payments'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='event.EventType'),
        ),
        migrations.AlterField(
            model_name='event',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='event.Week'),
        ),
        migrations.AlterField(
            model_name='eventanket',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='event_anket', to='account.CustomUser'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='home_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='group.HomeGroup', verbose_name='Домашняя группа'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event/49/', verbose_name='Event Image'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.CustomUser'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'in_progress'), (2, 'submitted'), (3, 'expired')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.MeetingType', verbose_name='Meeting type'),
        ),
        migrations.AlterField(
            model_name='meetingattend',
            name='attended',
            field=models.BooleanField(default=False, verbose_name='Attended'),
        ),
        migrations.AlterField(
            model_name='meetingattend',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attends', to='event.Meeting', verbose_name='Meeting'),
        ),
        migrations.AlterField(
            model_name='meetingattend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attends', to='account.CustomUser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='event.Event'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='event.EventAnket'),
        ),
    ]
