# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0044_auto_20171210_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event/51/', verbose_name='Event Image'),
        ),
    ]
