# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-27 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0045_auto_20171219_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchreport',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Church', verbose_name='Church'),
        ),
    ]
