# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-29 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0046_auto_20171227_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingattend',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attends', to='event.Meeting', verbose_name='Meeting'),
        ),
    ]
