# Generated by Django 2.0.1 on 2018-01-26 17:55

import apps.payment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0047_auto_20171229_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchreport',
            name='donations',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=12, verbose_name='Donations'),
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='pastor_tithe',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=12, verbose_name='Pastor Tithe'),
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='tithe',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=12, verbose_name='Tithe'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='total_sum',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=12, verbose_name='Total sum'),
        ),
    ]
