# Generated by Django 2.0.2 on 2018-02-06 15:19

import apps.payment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0048_auto_20180126_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchreport',
            name='pastor_tithe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Pastor Tithe'),
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='tithe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tithe'),
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='transfer_payments',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Transfer Payments'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total sum'),
        ),
    ]
