# Generated by Django 2.0.2 on 2018-03-04 04:32

import apps.payment.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0049_auto_20180206_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchreport',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Church', verbose_name='Церковь'),
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='currency',
            field=models.ForeignKey(default=apps.payment.models.get_default_currency, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.Currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='donations',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Donations'),
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='pastor',
            field=models.ForeignKey(limit_choices_to={'hierarchy__level__gte': 2}, on_delete=django.db.models.deletion.PROTECT, to='account.CustomUser'),
        ),
        migrations.AlterField(
            model_name='event',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='home_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.HomeGroup', verbose_name='Домашняя группа'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event/9/', verbose_name='Event Image'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'hierarchy__level__gte': 1}, on_delete=django.db.models.deletion.PROTECT, to='account.CustomUser'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='week',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='week',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
