# Generated by Django 2.0.2 on 2018-03-06 14:34

import common.date_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0050_auto_20180304_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='from_date',
            field=models.DateField(default=common.date_utils.today),
        ),
        migrations.AlterField(
            model_name='event',
            name='to_date',
            field=models.DateField(default=common.date_utils.today),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event/10/', verbose_name='Event Image'),
        ),
        migrations.AlterField(
            model_name='week',
            name='from_date',
            field=models.DateField(default=common.date_utils.today),
        ),
        migrations.AlterField(
            model_name='week',
            name='to_date',
            field=models.DateField(default=common.date_utils.today),
        ),
    ]
