# Generated by Django 2.0.4 on 2018-04-25 08:53

import apps.event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0051_auto_20180306_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.event.models.get_event_week, verbose_name='Event Image'),
        ),
    ]
