# Generated by Django 2.0.5 on 2018-05-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0052_auto_20180425_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='guest_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Guest count'),
        ),
    ]
