# Generated by Django 2.0.5 on 2018-05-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0053_meeting_guest_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='new_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='New count'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='repentance_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Repentance count'),
        ),
    ]
