# Generated by Django 2.0.6 on 2018-06-14 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0022_auto_20180611_0718'),
        ('account', '0045_customuser_is_proposal_manager'),
        ('event', '0054_auto_20180530_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingattend',
            name='church',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='group.Church', verbose_name='Церковь'),
        ),
        migrations.AddField(
            model_name='meetingattend',
            name='home_group',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='group.HomeGroup', verbose_name='Home group'),
        ),
        migrations.AddField(
            model_name='meetingattend',
            name='is_stable',
            field=models.NullBooleanField(editable=False, verbose_name='Is Stable'),
        ),
        migrations.AddField(
            model_name='meetingattend',
            name='master',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.CustomUser', verbose_name='Ответственный'),
        ),
    ]
