# Generated by Django 2.0.8 on 2018-09-05 13:39

import apps.payment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0055_auto_20180614_0607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchreport',
            options={'ordering': ('-id', '-date'), 'verbose_name': 'Church Report', 'verbose_name_plural': 'Church Reports'},
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Church', verbose_name='Church'),
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='currency',
            field=models.ForeignKey(default=apps.payment.models.get_default_currency, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.Currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'in_progress'), (2, 'submitted'), (3, 'expired')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='home_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.HomeGroup', verbose_name='Home Group'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'in_progress'), (2, 'submitted'), (3, 'expired')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total sum'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='visitors',
            field=models.ManyToManyField(related_name='meeting_types', through='event.MeetingAttend', to='account.CustomUser', verbose_name='Visitors'),
        ),
        migrations.AlterField(
            model_name='meetingattend',
            name='church',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='group.Church', verbose_name='Church'),
        ),
        migrations.AlterField(
            model_name='meetingattend',
            name='master',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.CustomUser', verbose_name='Master'),
        ),
        migrations.AlterField(
            model_name='meetingattend',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='code',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
