# Generated by Django 2.0.8 on 2018-09-13 09:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_auto_20180306_1434'),
        ('event', '0056_auto_20180905_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.Currency', verbose_name='Donation currency'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='donation',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Donation'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='tithe',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Donation'),
        ),
    ]
