# Generated by Django 2.0.8 on 2018-09-14 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0057_auto_20180913_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='tithe',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tithe'),
        ),
    ]
