# Generated by Django 2.0.8 on 2018-10-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab_column', '0001_initial'),
        ('event', '0059_meetingtype_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingtype',
            name='columns',
        ),
        migrations.AddField(
            model_name='meetingtype',
            name='columns_with_church',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types_with_church', to='tab_column.Table', verbose_name='Колонки с привязкой'),
        ),
        migrations.AddField(
            model_name='meetingtype',
            name='columns_without_church',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types_without_church', to='tab_column.Table', verbose_name='Колонки без привязки'),
        ),
    ]
