# Generated by Django 2.0.8 on 2018-10-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_auto_20180705_0758'),
        ('event', '0060_auto_20181005_1435'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetingattend',
            unique_together={('user', 'meeting')},
        ),
    ]
