# Generated by Django 2.0.9 on 2018-10-26 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0060_auto_20181005_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingattend',
            name='donate',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='10%'),
        ),
    ]
