# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0001_initial'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayreport',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_reports', to='hierarchy.Department'),
        ),
        migrations.AddField(
            model_name='monthreport',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month_reports', to='hierarchy.Department'),
        ),
        migrations.AddField(
            model_name='yearreport',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_reports', to='hierarchy.Department'),
        ),
    ]
