# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20170214_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='homegroup',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
