# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 13:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_auto_20170828_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='report_currency',
            field=models.IntegerField(default=2, verbose_name='Report Currency'),
        ),
    ]
