# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-05 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0013_customuser_spiritual_level'),
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Title')),
                ('opening_date', models.DateField(default=timezone.now, verbose_name='Opening Date')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('phone_number', models.CharField(blank=True, max_length=13, verbose_name='Phone Number')),
                ('website', models.URLField(blank=True, verbose_name='Web Site')),
                ('is_open', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='churches', to='hierarchy.Department', verbose_name='Department')),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='church', to='account.CustomUser', verbose_name='Pastor')),
                ('users', models.ManyToManyField(blank=True, related_name='churches', to='account.CustomUser', verbose_name='Users')),
            ],
            options={
                'verbose_name': 'Church',
                'verbose_name_plural': 'Churches',
            },
        ),
        migrations.CreateModel(
            name='HomeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Title')),
                ('opening_date', models.DateField(default=timezone.now, verbose_name='Opening Date')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('phone_number', models.CharField(blank=True, max_length=13, verbose_name='Phone Number')),
                ('website', models.URLField(blank=True, verbose_name='Web Site')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_group', to='group.Church', verbose_name='Church')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_group', to='account.CustomUser', verbose_name='Leader')),
                ('users', models.ManyToManyField(blank=True, related_name='home_groups', to='account.CustomUser', verbose_name='Users')),
            ],
            options={
                'verbose_name': 'Home Group',
                'verbose_name_plural': 'Home Groups',
            },
        ),
    ]
