# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 15:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_homegroup_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'ordering': ['-opening_date', '-id'], 'verbose_name': 'Церковь', 'verbose_name_plural': 'Церкви'},
        ),
        migrations.AlterModelOptions(
            name='homegroup',
            options={'ordering': ['-opening_date', '-id'], 'verbose_name': 'Домашняя группа', 'verbose_name_plural': 'Домашние группы'},
        ),
        migrations.RemoveField(
            model_name='church',
            name='users',
        ),
        migrations.RemoveField(
            model_name='homegroup',
            name='users',
        ),
        migrations.AlterField(
            model_name='church',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='church',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='church',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='churches', to='hierarchy.Department', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='church',
            name='opening_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата открытия'),
        ),
        migrations.AlterField(
            model_name='church',
            name='pastor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='church', to='account.CustomUser', verbose_name='Пастор'),
        ),
        migrations.AlterField(
            model_name='church',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='church',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заглавие'),
        ),
        migrations.AlterField(
            model_name='church',
            name='website',
            field=models.URLField(blank=True, verbose_name='Веб сайт'),
        ),
        migrations.AlterField(
            model_name='homegroup',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_group', to='group.Church', verbose_name='Церковь'),
        ),
        migrations.AlterField(
            model_name='homegroup',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='homegroup',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_group', to='account.CustomUser', verbose_name='Лидер'),
        ),
        migrations.AlterField(
            model_name='homegroup',
            name='opening_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата открытия'),
        ),
        migrations.AlterField(
            model_name='homegroup',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='homegroup',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заглавие'),
        ),
        migrations.AlterField(
            model_name='homegroup',
            name='website',
            field=models.URLField(blank=True, verbose_name='Веб сайт'),
        ),
    ]
