# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_auto_20170725_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='homegroup',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
