# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_auto_20170829_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homegroup',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_group', to='group.Church', verbose_name='Church'),
        ),
    ]
