# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_auto_20170925_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homegroup',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_group', to='group.Church', verbose_name='Церковь'),
        ),
    ]
