# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-13 14:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_auto_20171210_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
    ]
