# Generated by Django 2.0.1 on 2018-01-05 12:34

import apps.payment.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_auto_20171219_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='churches/', verbose_name='Church Image'),
        ),
        migrations.AddField(
            model_name='homegroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home_groups/', verbose_name='Home Group Image'),
        ),
    ]
