# Generated by Django 2.0.1 on 2018-01-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_auto_20180105_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Region'),
        ),
    ]
