# Generated by Django 2.0.1 on 2018-02-01 12:10

import apps.payment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_district'),
        ('group', '0016_auto_20180112_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='locality',
            field=models.ForeignKey(blank=True, help_text='City/village/etc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='churches', to='location.City', verbose_name='Locality'),
        ),
        migrations.AddField(
            model_name='homegroup',
            name='locality',
            field=models.ForeignKey(blank=True, help_text='City/village/etc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_groups', to='location.City', verbose_name='Locality'),
        ),
        migrations.AlterField(
            model_name='church',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='church',
            name='report_currency',
            field=models.IntegerField(default=apps.payment.models.get_default_currency, verbose_name='Report Currency'),
        ),
    ]
