# Generated by Django 2.0.2 on 2018-03-04 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0018_auto_20180220_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='opening_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата открытия'),
        ),
        migrations.AlterField(
            model_name='homegroup',
            name='opening_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата открытия'),
        ),
    ]
