# Generated by Django 2.0.2 on 2018-03-06 14:34

import common.date_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0019_auto_20180304_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='opening_date',
            field=models.DateField(default=common.date_utils.today, verbose_name='Дата открытия'),
        ),
        migrations.AlterField(
            model_name='homegroup',
            name='opening_date',
            field=models.DateField(default=common.date_utils.today, verbose_name='Дата открытия'),
        ),
    ]
