# Generated by Django 2.0.6 on 2018-06-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0021_auto_20180522_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='title',
            field=models.CharField(max_length=40, unique=True, verbose_name='Заглавие'),
        ),
    ]
