# Generated by Django 2.0.6 on 2018-06-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0022_auto_20180611_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='title',
        ),
        migrations.AddField(
            model_name='direction',
            name='title_de',
            field=models.CharField(blank=True, max_length=40, verbose_name='Title de'),
        ),
        migrations.AddField(
            model_name='direction',
            name='title_en',
            field=models.CharField(blank=True, max_length=40, verbose_name='Title en'),
        ),
        migrations.AddField(
            model_name='direction',
            name='title_ru',
            field=models.CharField(blank=True, max_length=40, verbose_name='Title ru'),
        ),
    ]
