# Generated by Django 2.0.6 on 2018-06-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0023_auto_20180614_1233'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM group_homegroup_directions;DELETE FROM group_direction;")
    ]
