# Generated by Django 2.0.6 on 2018-06-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0024_delete_directions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='title_de',
            field=models.CharField(max_length=40, unique=True, verbose_name='Title de'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='title_en',
            field=models.CharField(max_length=40, unique=True, verbose_name='Title en'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='title_ru',
            field=models.CharField(max_length=40, unique=True, verbose_name='Title ru'),
        ),
    ]
