# Generated by Django 2.0.8 on 2018-10-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0026_auto_20180905_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homegroup',
            name='directions',
            field=models.ManyToManyField(blank=True, related_name='home_groups', to='group.Direction'),
        ),
    ]
