# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-29 13:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(default=datetime.date(2016, 4, 29))),
                ('to_date', models.DateField(default=datetime.date(2016, 4, 29))),
                ('time', models.TimeField(default=datetime.datetime(2016, 4, 29, 13, 46, 2, 303848, tzinfo=utc))),
            ],
            options={
                'verbose_name_plural': '\u0421\u043e\u0431\u044b\u0442\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='EventAnket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_anket', to='account.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/eventTypes/')),
                ('home', models.BooleanField(default=False)),
                ('night', models.BooleanField(default=False)),
                ('service', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(default=False)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(default=0)),
                ('count_as_leader', models.IntegerField(default=0)),
                ('value_as_leader', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='event.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='event.EventAnket')),
            ],
            options={
                'verbose_name_plural': '\u0423\u0447\u0430\u0441\u0442\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(default=17, unique=True)),
                ('from_date', models.DateField(default=datetime.date(2016, 4, 29))),
                ('to_date', models.DateField(default=datetime.date(2016, 4, 29))),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.EventType'),
        ),
        migrations.AddField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='events', through='event.Participation', to='event.EventAnket'),
        ),
        migrations.AddField(
            model_name='event',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Week'),
        ),
    ]
