# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-14 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_auto_20160914_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.datetime(2016, 9, 14, 14, 10, 12, 605806, tzinfo=utc)),
        ),
    ]
