# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-23 12:31
from __future__ import unicode_literals

from django.db import migrations


def create_meeting_types(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    MeetingType = apps.get_model("event", "MeetingType")

    MeetingType.objects.bulk_create([
        MeetingType(name='Служение', code='service'),
        MeetingType(name='Домашняя', code='home'),
        MeetingType(name='Ночная', code='night'),
    ])


def delete_meeting_types(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    MeetingType = apps.get_model("event", "MeetingType")

    MeetingType.objects.filter(code__in=('service', 'home', 'night')).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_auto_20161223_1420'),
    ]

    operations = [
        migrations.RunPython(create_meeting_types, delete_meeting_types),
    ]
