# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_auto_20170418_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchreport',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'in_progress'), (2, 'submitted'), (3, 'expired')], default=1, verbose_name='Status'),
        ),
    ]
