# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_auto_20170525_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchreport',
            options={'ordering': ('-id', '-date'), 'verbose_name': 'Отчет церкви', 'verbose_name_plural': 'Отчеты церкви'},
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='group.Church', verbose_name='Церковь'),
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'in_progress'), (2, 'submitted'), (3, 'expired')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='home_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.HomeGroup', verbose_name='Домашняя группа'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'in_progress'), (2, 'submitted'), (3, 'expired')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='total_sum',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='visitors',
            field=models.ManyToManyField(related_name='meeting_types', through='event.MeetingAttend', to='account.CustomUser', verbose_name='Посетители'),
        ),
        migrations.AlterField(
            model_name='meetingattend',
            name='note',
            field=models.TextField(blank=True, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='code',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Фото'),
        ),
    ]
