# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_auto_20170525_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchreport',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
    ]
