# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_auto_20170613_1554'),
        ('event', '0033_churchreport_comment'),
    ]

    operations = [
    ]
