# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_auto_20170713_1530'),
        ('event', '0033_auto_20170613_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchReportPastor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_report_pastor', to='account.CustomUser', verbose_name='Church Report Pastor')),
            ],
            options={
                'verbose_name_plural': 'Church Report Pastors',
                'verbose_name': 'Church Report Pastor',
            },
        ),
        migrations.AlterModelOptions(
            name='churchreport',
            options={'ordering': ('-id', '-date'), 'verbose_name': 'Church Report', 'verbose_name_plural': 'Church Reports'},
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='group.Church', verbose_name='Church'),
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'in_progress'), (2, 'submitted'), (3, 'expired')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='home_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.HomeGroup', verbose_name='Home Group'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'in_progress'), (2, 'submitted'), (3, 'expired')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='total_sum',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total sum'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='visitors',
            field=models.ManyToManyField(related_name='meeting_types', through='event.MeetingAttend', to='account.CustomUser', verbose_name='Visitors'),
        ),
        migrations.AlterField(
            model_name='meetingattend',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='code',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение'),
        ),
    ]
