# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0034_auto_20170725_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchreport',
            name='pastor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.ChurchReportPastor'),
        ),
    ]
