# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0040_auto_20170828_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchreport',
            name='pastor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.CustomUser'),
        ),
    ]
