# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0039_auto_20170821_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchreport',
            name='currency',
            field=models.ForeignKey(default=payment.models.get_default_currency, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.Currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='churchreport',
            name='transfer_payments',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=12, verbose_name='Transfer Payments'),
        ),
        migrations.AlterField(
            model_name='churchreportpastor',
            name='currency',
            field=models.ForeignKey(default=payment.models.get_default_currency, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.Currency', verbose_name='Валюта'),
        ),
    ]
