# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0040_auto_20170823_1129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChurchReportPastor',
        )
    ]
