# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0041_auto_20170823_1134'),
        ('event', '0040_auto_20170828_1600'),
    ]

    operations = [
    ]
