# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0042_auto_20170905_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=event.models.get_event_week, verbose_name='Event Image'),
        ),
    ]
