# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
