# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='district',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
