# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20160126_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hierarchy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='hierarchy.Hierarchy'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciples', to='account.CustomUser'),
        ),
    ]
