# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-29 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.IntegerField()),
                ('description', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('date', models.DateField(default=timezone.now)),
                ('is_responsible', models.BooleanField(default=False)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciples', to='partnership.Partnership')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partnership', to='account.CustomUser')),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='partnership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='partnership.Partnership'),
        ),
    ]
