# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-31 09:08
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0002_auto_20160504_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='date',
            field=models.DateField(default=timezone.now),
        ),
    ]
