# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-07 10:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0005_auto_20160603_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='date',
            field=models.DateField(default=datetime.date(2016, 6, 7)),
        ),
    ]
