# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-28 11:51
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0009_auto_20160621_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='date',
            field=models.DateField(default=timezone.now),
        ),
    ]
