# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-01 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('partnership', '0019_auto_20161101_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnership',
            name='is_responsible',
        ),
    ]
