# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-28 11:26
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0022_auto_20161107_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='value',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='value',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12),
        ),
    ]
