# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 10:59
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations


def create_payments(apps, schema_editor):
    Deal = apps.get_model("partnership", "Deal")
    Payment = apps.get_model("payment", "Payment")
    Currency = apps.get_model("payment", "Currency")
    ContentType = apps.get_model("contenttypes", "ContentType")
    uah = Currency.objects.get(code='uah')

    deals = Deal.objects.filter(done=True)
    create_deals = list()
    for deal in deals:
        create_deals.append(Payment(
            sum=deal.value,
            effective_sum=deal.value,
            description=deal.description,
            created_at=deal.date or deal.date_created,
            currency_sum=uah,
            currency_rate=uah,
            rate=Decimal(1),
            content_type=ContentType.objects.get_for_model(Deal),
            object_id=deal.id
        ))
    Payment.objects.bulk_create(create_deals)


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0024_auto_20170105_1514'),
    ]

    operations = [
        migrations.RunPython(create_payments),
    ]
