# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 13:50
from __future__ import unicode_literals

from django.db import migrations


def update_deal_responsible(apps, schema_editor):
    Deal = apps.get_model("partnership", "Deal")

    for deal in Deal.objects.all():
        deal.responsible = deal.partnership.responsible
        deal.save()


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0027_deal_responsible'),
    ]

    operations = [
        migrations.RunPython(update_deal_responsible),
    ]
