# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 11:27
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import apps.payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_payment_operation'),
        ('partnership', '0030_merge_20170412_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('date', models.DateField(default=datetime.date.today)),
                ('need_text', models.CharField(blank=True, max_length=600, verbose_name='Need text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Director'), (1, 'Supervisor'), (2, 'Manager'), (3, 'Partner')], default=3, verbose_name='Level')),
                ('plan', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Manager plan')),
                ('log_date', models.DateTimeField(auto_now_add=True, verbose_name='Log date')),
                ('currency', models.ForeignKey(default=apps.payment.models.get_default_currency, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.Currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Partnership Log',
                'ordering': ('-log_date',),
                'verbose_name_plural': 'Partnership Logs',
            },
        ),
        migrations.AddField(
            model_name='partnership',
            name='plan',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Manager plan'),
        ),
        migrations.AddField(
            model_name='partnershiplogs',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner', to='partnership.Partnership', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='partnershiplogs',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciples', to='partnership.PartnershipLogs'),
        ),
    ]
