# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0032_auto_20170912_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Donation'), (2, 'Tithe')], default=1, verbose_name='Deal type'),
        ),
    ]
