# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 10:00
from __future__ import unicode_literals

from django.db import migrations


def set_user_as_responsible(apps, schema_editor):
    Partnership = apps.get_model("partnership", "Partnership")
    PartnershipLogs = apps.get_model("partnership", "PartnershipLogs")
    Deal = apps.get_model("partnership", "Deal")

    for p in Partnership.objects.all():
        p.uresponsible = p.responsible.user if p.responsible else None
        p.save()
    for p in PartnershipLogs.objects.all():
        p.uresponsible = p.responsible.user if p.responsible else None
        p.save()
    for d in Deal.objects.all():
        d.uresponsible = d.responsible.user if d.responsible else None
        d.save()


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0037_auto_20171013_0959'),
    ]

    operations = [
        migrations.RunPython(set_user_as_responsible),
    ]
