# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0039_delete_partner_responsible_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='uresponsible',
            new_name='responsible',
        ),
        migrations.RenameField(
            model_name='partnership',
            old_name='uresponsible',
            new_name='responsible',
        ),
        migrations.RenameField(
            model_name='partnershiplogs',
            old_name='uresponsible',
            new_name='responsible',
        ),
    ]
