# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 15:34
from __future__ import unicode_literals

from django.db import migrations


def copy_plan(apps, schema_editor):
    PartnerRole = apps.get_model("partnership", "PartnerRole")

    for partner_role in PartnerRole.objects.all():
        partner = partner_role.user.partners.first()
        partner_role.plan = partner.plan if partner else None
        partner_role.save()


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0042_add_plan_field_to_partnerrole'),
    ]

    operations = [
        migrations.RunPython(copy_plan),
    ]
