# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_auto_20171004_1634'),
        ('partnership', '0043_copy_plan_from_partner_to_partnerrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerRoleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(editable=False, verbose_name='Level')),
                ('plan', models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=12, null=True, verbose_name='Manager plan')),
                ('log_date', models.DateTimeField(auto_now_add=True, verbose_name='Log date')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='partner_role_logs', to='account.CustomUser')),
            ],
            options={
                'verbose_name': 'Partner role Log',
                'verbose_name_plural': 'Partner role Logs',
                'ordering': ('-log_date',),
            },
        ),
    ]
