# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0048_add_partner_group_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Partner title'),
        ),
        migrations.AddField(
            model_name='partnershiplogs',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Partner title'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='partnership.PartnerGroup', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_disciples', to='account.CustomUser', verbose_name='Responsible'),
        ),
    ]
