# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0050_add_index_for_partner_log_date_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='title',
            field=models.CharField(choices=[('UA', 'UA'), ('EU', 'EU')], default='UA', max_length=255, verbose_name='Partner title'),
        ),
        migrations.AlterField(
            model_name='partnershiplogs',
            name='title',
            field=models.CharField(choices=[('UA', 'UA'), ('EU', 'EU')], default='UA', max_length=255, verbose_name='Partner title'),
        ),
        migrations.AlterUniqueTogether(
            name='partnership',
            unique_together=set([]),
        ),
    ]
