# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0052_set_parter_title_eq_UA'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='partnership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='partnership.Partnership'),
        ),
        migrations.AlterField(
            model_name='partnerrole',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='partner_role', to='account.CustomUser'),
        ),
        migrations.AlterField(
            model_name='partnerrolelog',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='partner_role_logs', to='account.CustomUser'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='account.CustomUser'),
        ),
    ]
