# Generated by Django 2.0.1 on 2018-01-29 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_auto_20171228_1509'),
        ('partnership', '0054_auto_20171210_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название Группы')),
                ('join_url', models.URLField(verbose_name='Ссылка на группу')),
            ],
            options={
                'verbose_name_plural': 'Группы в Telegram',
                'verbose_name': 'Группа в Telegram',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(verbose_name='Telegram ID')),
                ('group_id', models.IntegerField(verbose_name='Group ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active Partner')),
                ('synced', models.BooleanField(default=True, verbose_name='Is synced?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_users', to='account.CustomUser', verbose_name='Telegram User')),
            ],
            options={
                'verbose_name_plural': 'Пользователи Telegram',
                'verbose_name': 'Пользователь Telegram',
                'ordering': ('-id',),
            },
        )
    ]
