# Generated by Django 2.0.2 on 2018-03-06 14:34

import common.date_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0056_auto_20180304_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchdeal',
            name='date_created',
            field=models.DateField(blank=True, default=common.date_utils.today, null=True),
        ),
        migrations.AlterField(
            model_name='churchpartner',
            name='date',
            field=models.DateField(default=common.date_utils.today),
        ),
        migrations.AlterField(
            model_name='churchpartnerlog',
            name='date',
            field=models.DateField(default=common.date_utils.today),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date_created',
            field=models.DateField(blank=True, default=common.date_utils.today, null=True),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='date',
            field=models.DateField(default=common.date_utils.today),
        ),
        migrations.AlterField(
            model_name='partnershiplogs',
            name='date',
            field=models.DateField(default=common.date_utils.today),
        ),
    ]
