# Generated by Django 2.0.3 on 2018-04-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0057_auto_20180306_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroup',
            name='bot_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bot address'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
