# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-07 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitanket',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='summitanket',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
