# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-13 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0005_summitanket_bishop'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitanket',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='summitanket',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
