# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-20 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('summit', '0015_auto_20160922_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitanket',
            name='log',
            field=models.BooleanField(default=False),
        ),
    ]
