# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-21 13:33
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0004_auto_20160922_1056'),
        ('summit', '0015_auto_20160922_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummitAnketNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Note')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime created')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='notes', to='account.CustomUser',
                                            verbose_name='Owner of note')),
                ('summit_anket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes',
                                                   to='summit.SummitAnket', verbose_name='Summit anket')),
            ],
            options={
                'verbose_name_plural': 'Summit Anket Notes',
                'verbose_name': 'Summit Anket Note',
            },
        ),
    ]
