# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-20 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('summit', '0016_summitanket_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summitanket',
            name='log',
        ),
    ]
