# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 12:29
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('summit', '0017_auto_20161024_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummitLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('summit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons',
                                             to='summit.Summit', verbose_name='Summit')),
                ('viewers',
                 models.ManyToManyField(related_name='all_lessons', to='summit.SummitAnket', verbose_name='Viewers')),
            ],
            options={
                'verbose_name_plural': 'Summit lessons',
                'ordering': ('summit', 'name'),
                'verbose_name': 'Summit lesson',
            },
        ),
        migrations.AlterUniqueTogether(
            name='summitlesson',
            unique_together=set([('name', 'summit')]),
        ),
    ]
