# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-14 10:13
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('summit', '0018_auto_20161026_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summitanketnote',
            options={'ordering': ('date_created',), 'verbose_name': 'Summit Anket Note',
                     'verbose_name_plural': 'Summit Anket Notes'},
        ),
        migrations.AddField(
            model_name='summitanket',
            name='visited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='summitlesson',
            name='summit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons',
                                    related_query_name='lessons', to='summit.Summit', verbose_name='Summit'),
        ),
    ]
