# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-22 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('summit', '0024_auto_20161121_1148'),
        ('summit', '0024_auto_20161118_1439'),
    ]

    operations = [
    ]
