# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-02 10:05
from __future__ import unicode_literals

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('summit', '0026_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='summit',
            name='code',
            field=models.SlugField(blank=True, max_length=255, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='summit',
            name='full_cost',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Full cost'),
        ),
        migrations.AddField(
            model_name='summit',
            name='special_cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True,
                                      verbose_name='Special cost'),
        ),
        migrations.AddField(
            model_name='summittype',
            name='code',
            field=models.SlugField(blank=True, max_length=255, verbose_name='Code'),
        ),
    ]
