# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-02 10:38
from __future__ import unicode_literals

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('summit', '0027_auto_20161202_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summitanket',
            name='value',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12,
                                      verbose_name='Paid amount'),
        ),
    ]
