# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-05 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('summit', '0028_auto_20161202_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summittype',
            options={'verbose_name': 'Summit Type', 'verbose_name_plural': 'Summits Types'},
        ),
    ]
