# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-06 15:06
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dbmail', '0013_auto_20160923_2201'),
        ('summit', '0029_auto_20161205_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='summit',
            name='mail_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='summits', to='dbmail.MailTemplate', verbose_name='Mail template'),
        ),
    ]
