# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-20 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('summit', '0032_anketemail_is_success'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summitanket',
            options={'ordering': ('summit__type', '-summit__start_date')},
        ),
        migrations.AlterModelOptions(
            name='summitanketnote',
            options={'ordering': ('-date_created',), 'verbose_name': 'Summit Anket Note',
                     'verbose_name_plural': 'Summit Anket Notes'},
        ),
    ]
