# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-06 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0033_auto_20170105_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summitanket',
            options={'ordering': ('summit__type', '-summit__start_date')},
        ),
        migrations.AlterModelOptions(
            name='summitanketnote',
            options={'ordering': ('-date_created',), 'verbose_name': 'Summit Anket Note', 'verbose_name_plural': 'Summit Anket Notes'},
        ),
    ]
