# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-06 09:42
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations


def create_payments(apps, schema_editor):
    SummitAnket = apps.get_model("summit", "SummitAnket")
    Payment = apps.get_model("payment", "Payment")
    Currency = apps.get_model("payment", "Currency")
    ContentType = apps.get_model("contenttypes", "ContentType")
    uah = Currency.objects.get(code='uah')

    ankets = SummitAnket.objects.filter(value__gt=0)
    create_ankets = list()
    for anket in ankets:
        create_ankets.append(Payment(
            sum=anket.value,
            effective_sum=anket.value,
            description=anket.description,
            created_at=anket.summit.start_date,
            currency_sum=uah,
            currency_rate=uah,
            rate=Decimal(1),
            content_type=ContentType.objects.get_for_model(SummitAnket),
            object_id=anket.id
        ))
    Payment.objects.bulk_create(create_ankets)


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0034_auto_20170106_1142'),
    ]

    operations = [
        migrations.RunPython(create_payments),
    ]
