# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-06 14:33
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0035_auto_20170106_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summitanket',
            name='value',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), editable=False, max_digits=12, verbose_name='Paid amount'),
        ),
    ]
