# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 10:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
        ('account', '0024_auto_20170504_1303'),
        ('hierarchy', '0001_initial'),
        ('summit', '0039_auto_20170503_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summitanket',
            name='image',
        ),
        migrations.RemoveField(
            model_name='summitanket',
            name='name',
        ),
        migrations.RemoveField(
            model_name='summitanket',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='summitanket',
            name='region',
        ),
        migrations.AddField(
            model_name='summitanket',
            name='bishop_fk',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bishop_users', to='account.CustomUser', verbose_name='Bishop'),
        ),
        migrations.AddField(
            model_name='summitanket',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_profiles', to='account.CustomUser', verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='summitanket',
            name='departments',
            field=models.ManyToManyField(editable=False, to='hierarchy.Department', verbose_name='Departments'),
        ),
        migrations.AddField(
            model_name='summitanket',
            name='divisions',
            field=models.ManyToManyField(editable=False, to='status.Division', verbose_name='Divisions'),
        ),
        migrations.AddField(
            model_name='summitanket',
            name='divisions_title',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='Divisions title'),
        ),
        migrations.AddField(
            model_name='summitanket',
            name='hierarchy',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hierarchy.Hierarchy', verbose_name='Hierarchy'),
        ),
        migrations.AddField(
            model_name='summitanket',
            name='hierarchy_title',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='summitanket',
            name='master',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='summit.SummitAnket', verbose_name='Master'),
        ),
        migrations.AddField(
            model_name='summitanket',
            name='middle_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Middle name'),
        ),
        migrations.AddField(
            model_name='summitanket',
            name='pastor_fk',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pastor_users', to='account.CustomUser', verbose_name='Pastor'),
        ),
        migrations.AddField(
            model_name='summitanket',
            name='search_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Field for search by name'),
        ),
        migrations.AddField(
            model_name='summitanket',
            name='sotnik_fk',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sotnik_users', to='account.CustomUser', verbose_name='Sotnik'),
        ),
        migrations.AddField(
            model_name='summitanket',
            name='spiritual_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Baby'), (2, 'Junior'), (3, 'Father')], default=1, verbose_name='Spiritual Level'),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='bishop',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='country',
            field=models.CharField(blank=True, max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='date',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='department',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='first_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='last_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='pastor',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='responsible',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='sotnik',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
