# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0040_auto_20170504_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summitanket',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
