# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0041_auto_20170504_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summitanket',
            name='master',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.CustomUser', verbose_name='Master'),
        ),
    ]
