# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0044_auto_20170505_1046'),
        ('summit', '0040_summiteventtable'),
    ]

    operations = [
    ]
