# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0045_merge_20170515_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summiteventtable',
            options={'ordering': ('-id',), 'verbose_name': 'Расписание Саммита', 'verbose_name_plural': 'Расписание Саммита'},
        ),
        migrations.AddField(
            model_name='summitticket',
            name='is_printed',
            field=models.BooleanField(default=False, verbose_name='Is printed'),
        ),
    ]
