# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0047_auto_20170517_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummitAttend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('anket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attends', to='summit.SummitAnket', verbose_name='Anket')),
            ],
            options={
                'verbose_name': 'Summit Attend',
                'verbose_name_plural': 'Summit Attends',
                'ordering': ('-date',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='summitattend',
            unique_together=set([('anket', 'date')]),
        ),
    ]
