# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0046_merge_20170517_1440'),
        ('summit', '0047_auto_20170517_1524'),
    ]

    operations = [
    ]
