# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0048_merge_20170519_0912'),
        ('summit', '0048_merge_20170522_1037'),
    ]

    operations = [
    ]
