# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0049_merge_20170523_1132'),
        ('summit', '0049_merge_20170522_1040'),
    ]

    operations = [
    ]
