# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0050_merge_20170526_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summiteventtable',
            name='author_de',
            field=models.CharField(blank=True, max_length=64, verbose_name='Имя автора на Немецком'),
        ),
        migrations.AlterField(
            model_name='summiteventtable',
            name='author_en',
            field=models.CharField(blank=True, max_length=64, verbose_name='Имя автора на Английском'),
        ),
        migrations.AlterField(
            model_name='summiteventtable',
            name='author_ru',
            field=models.CharField(blank=True, max_length=64, verbose_name='Имя автора на Русском'),
        ),
    ]
