# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0053_anketstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketstatus',
            name='reg_code_requested_date',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Дата ввода регистрационного кода'),
        ),
    ]
