# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0057_auto_20170615_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summitanket',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='summitattend',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Date'),
        ),
    ]
