# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0058_auto_20170619_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summitvisitorlocation',
            name='date_time',
            field=models.DateTimeField(db_index=True, verbose_name='Date Time'),
        ),
    ]
