# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0059_auto_20170619_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitattend',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
    ]
