# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 16:47
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0063_auto_20170713_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitanket',
            name='master_path',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(verbose_name='User id'), default=[], editable=False, size=None, verbose_name='Master path'),
        ),
    ]
