# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0006_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalphonenumber',
            name='number',
            field=models.CharField(max_length=255, verbose_name='Number'),
        ),
    ]
