# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-17 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('summit', '0023_auto_20161117_1108'),
        ('account', '0009_remove_customuser_summit_consultants'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='summit_consultants',
            field=models.ManyToManyField(related_name='users', through='summit.SummitUserConsultant',
                                         to='summit.Summit'),
        ),
    ]
