# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_customuser_spiritual_level'),
        ('account', '0013_customuser_search_name'),
    ]

    operations = [
    ]
