# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_remove_customuser_hierarchy_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=40, verbose_name='Activation key'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='born_date',
            field=models.DateField(blank=True, null=True, verbose_name='Born date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='coming_date',
            field=models.DateField(blank=True, null=True, verbose_name='Coming date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='departments',
            field=models.ManyToManyField(related_name='users', to='hierarchy.Department', verbose_name='Departments'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='district',
            field=models.CharField(blank=True, max_length=50, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='facebook',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hierarchy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='hierarchy.Hierarchy', verbose_name='Hierarchy'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_source',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Source of image'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='master',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disciples', to='account.CustomUser', verbose_name='Master'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='odnoklassniki',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Odnoklassniki URL'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=23, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, max_length=50, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='repentance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Repentance date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skype',
            field=models.CharField(blank=True, max_length=50, verbose_name='Skype'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vkontakte',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Vkontakte URL'),
        ),
    ]
