# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20170504_1303'),
        ('account', '0024_set_can_login'),
    ]

    operations = [
    ]
