# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 14:37
from __future__ import unicode_literals

from django.db import migrations


def set_managers(apps, schema_editor):
    CustomUser = apps.get_model("account", "CustomUser")

    users = CustomUser.objects.filter(manager__isnull=False)
    for u in users:
        u.managers.set([u.manager_id])


def reset_managers(apps, schema_editor):
    CustomUser = apps.get_model("account", "CustomUser")

    users = CustomUser.objects.filter(managers__isnull=False)
    for u in users:
        u.managers.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_auto_20171227_1437'),
    ]

    operations = [
        migrations.RunPython(set_managers, reset_managers),
    ]
