# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_auto_20171227_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='manager',
        ),
    ]
