# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_remove_customuser_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='skins', to='account.CustomUser', verbose_name='Manager'),
        ),
    ]
