# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-28 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_auto_20171227_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_dead',
            field=models.BooleanField(default=False, verbose_name='Is Dead'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_stable',
            field=models.BooleanField(default=True, verbose_name='Is Stable'),
        ),
    ]
