# Generated by Django 2.0.1 on 2018-01-29 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_district'),
        ('account', '0042_auto_20171228_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='locality',
            field=models.ForeignKey(blank=True, help_text='City/village/etc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='location.City', verbose_name='Locality'),
        ),
    ]
