# Generated by Django 2.0.5 on 2018-06-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_added_sex_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_proposal_manager',
            field=models.BooleanField(default=False, verbose_name='Is proposal manager'),
        ),
    ]
