# Generated by Django 2.0.6 on 2018-07-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_customuser_is_proposal_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('de', 'Germany')], default='RU', max_length=10, verbose_name='Language'),
        ),
    ]
