# Generated by Django 2.0.6 on 2018-07-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_auto_20180702_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('de', 'Germany')], default='ru', max_length=10, verbose_name='Language'),
        ),
    ]
