# Generated by Django 2.0.9 on 2018-10-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_auto_20180705_0758'),
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together={('test_id', 'user')},
        ),
    ]
