# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 16:05
from __future__ import unicode_literals

import apps.zmail.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZMailAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('filename', models.FileField(upload_to=apps.zmail.models._upload_mail_file, verbose_name='File')),
            ],
            options={
                'verbose_name': 'Mail file',
                'verbose_name_plural': 'Mail files',
            },
        ),
        migrations.CreateModel(
            name='ZMailAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, verbose_name='Host')),
                ('port', models.PositiveIntegerField(verbose_name='Port')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='Password')),
                ('use_tls', models.BooleanField(default=False, verbose_name='Use TLS')),
                ('fail_silently', models.BooleanField(default=False, verbose_name='Fail silently')),
            ],
            options={
                'verbose_name': 'Mail auth settings',
                'verbose_name_plural': 'Mail auth settings',
            },
        ),
        migrations.CreateModel(
            name='ZMailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Template name')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('from_email', models.CharField(blank=True, default=None, max_length=255, verbose_name='Message from')),
                ('message', tinymce.models.HTMLField(verbose_name='Body')),
                ('slug', models.SlugField(help_text='Unique slug to use in code.', unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('interval', models.PositiveIntegerField(blank=True, null=True, verbose_name='Send interval')),
                ('auth', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='zmail.ZMailAuth', verbose_name='Auth credentials')),
            ],
            options={
                'verbose_name': 'Mail template',
                'verbose_name_plural': 'Mail templates',
            },
        ),
        migrations.AddField(
            model_name='zmailattachment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='zmail.ZMailTemplate', verbose_name='Template'),
        ),
    ]
