# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-13 07:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0002_auto_20160607_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitanket',
            name='date',
            field=models.DateField(default=datetime.date(2016, 6, 13)),
        ),
        migrations.AddField(
            model_name='summitanket',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='summitanket',
            name='responsible',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
