# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-21 09:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0007_auto_20160617_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitanket',
            name='protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='date',
            field=models.DateField(default=datetime.date(2016, 6, 21)),
        ),
    ]
