# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-29 09:18
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0009_auto_20160628_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitanket',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='summitanket',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='summitanket',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='date',
            field=models.DateField(default=timezone.now),
        ),
    ]
