# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-01 09:37
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0010_auto_20160629_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitanket',
            name='image',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='summitanket',
            name='responsible',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='date',
            field=models.DateField(default=timezone.now),
        ),
    ]
