# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-01 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0011_auto_20160701_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitanket',
            name='retards',
            field=models.BooleanField(default=False),
        ),
    ]
