# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-14 14:05
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0012_summitanket_retards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summitanket',
            name='date',
            field=models.DateField(default=timezone.now),
        ),
    ]
