# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('summit', '0014_auto_20160921_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summitanket',
            name='bishop',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='code',
            field=models.CharField(blank=True, default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='country',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='image',
            field=models.CharField(blank=True, default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='pastor',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='region',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='responsible',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='sotnik',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summittype',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='summit_type/images/'),
            preserve_default=False,
        ),
    ]
