# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-14 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('summit', '0018_auto_20161026_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitanket',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
