# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-14 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('summit', '0019_auto_20161111_1133'),
        ('summit', '0019_auto_20161114_1213'),
    ]

    operations = [
    ]
