# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-17 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0009_remove_customuser_summit_consultants'),
        ('summit', '0021_summittype_club_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='summituserconsultant',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='summituserconsultant',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='summituserconsultant',
            name='summit_type',
        ),
        migrations.RemoveField(
            model_name='summituserconsultant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='summittype',
            name='consultants',
        ),
        migrations.AddField(
            model_name='summit',
            name='consultants',
            field=models.ManyToManyField(related_name='consultees_summits', to='account.CustomUser',
                                         verbose_name='Consultants'),
        ),
        migrations.DeleteModel(
            name='SummitUserConsultant',
        ),
    ]
