# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-17 09:08
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0009_remove_customuser_summit_consultants'),
        ('summit', '0022_auto_20161117_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummitUserConsultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultees',
                                                 to='account.CustomUser', verbose_name='Consultant')),
                ('summit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultees',
                                             to='summit.Summit', verbose_name='Summit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultants',
                                           to='account.CustomUser', verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Summit consultants',
                'verbose_name': 'Summit consultant',
            },
        ),
        migrations.AlterUniqueTogether(
            name='summituserconsultant',
            unique_together=set([('user', 'summit')]),
        ),
    ]
