# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-18 12:39
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('summit', '0023_auto_20161117_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summit',
            options={'ordering': ('type',), 'verbose_name': 'Summit', 'verbose_name_plural': 'Summits'},
        ),
        migrations.RemoveField(
            model_name='summit',
            name='consultants',
        ),
        migrations.AddField(
            model_name='summitanket',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Visitor'), (20, 'Consultant'), (30, 'Supervisor')],
                                                   default=10, verbose_name='Summit Role'),
        ),
        migrations.AddField(
            model_name='summitanket',
            name='summit_consultants',
            field=models.ManyToManyField(related_name='consultant_ankets', through='summit.SummitUserConsultant',
                                         to='summit.Summit'),
        ),
        migrations.AlterField(
            model_name='summituserconsultant',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultees',
                                    to='summit.SummitAnket', verbose_name='Consultant'),
        ),
        migrations.AlterField(
            model_name='summituserconsultant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultants',
                                    to='summit.SummitAnket', verbose_name='User'),
        ),
    ]
