# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-22 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('summit', '0024_auto_20161121_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitanket',
            name='ticket',
            field=models.FileField(blank=True, null=True, upload_to='tickets', verbose_name='Ticket'),
        ),
    ]
