# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-28 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0025_summitanket_ticket'),
        ('summit', '0025_merge'),
    ]

    operations = [
    ]
