# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-06 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('summit', '0029_auto_20161205_1756'),
    ]

    operations = [
    ]
