# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-05 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import apps.payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20170105_1514'),
        ('summit', '0032_anketemail_is_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='summit',
            name='currency',
            field=models.ForeignKey(default=apps.payment.models.get_default_currency, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.Currency', verbose_name='Currency'),
        ),
    ]
