# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20170314_1502'),
        ('summit', '0037_summitanket_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummitTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tickets', verbose_name='Ticket')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('status', models.CharField(choices=[('progress', 'In progress'), ('complete', 'Complete'), ('error', 'Error')], default='progress', max_length=20, verbose_name='Status')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to='account.CustomUser', verbose_name='User')),
                ('summit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='summit.Summit', verbose_name='Summit')),
                ('users', models.ManyToManyField(related_name='users', to='summit.SummitAnket', verbose_name='Users')),
            ],
            options={
                'verbose_name': 'Summit ticket',
                'verbose_name_plural': 'List of summit tickets',
                'ordering': ('summit', 'status'),
            },
        ),
    ]
