# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0038_summitticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummitVisitorLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Date Time')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_locations', to='summit.SummitAnket', verbose_name='Summit Visitor')),
            ],
            options={
                'verbose_name_plural': 'Summit Users Location',
                'verbose_name': 'Summit User Location',
                'ordering': ('-date_time',),
            },
        ),
        migrations.AlterModelOptions(
            name='summitticket',
            options={'ordering': ('summit', 'title'), 'verbose_name': 'Summit ticket', 'verbose_name_plural': 'List of summit tickets'},
        ),
        migrations.AlterField(
            model_name='summitticket',
            name='users',
            field=models.ManyToManyField(related_name='tickets', to='summit.SummitAnket', verbose_name='Users'),
        ),
        migrations.AlterUniqueTogether(
            name='summitvisitorlocation',
            unique_together=set([('visitor', 'date_time')]),
        ),
    ]
