# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 07:46
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Value as V
from django.db.models.functions import Concat


def _get_master_tree_by_level(user, level):
    master = user.master
    while master is not None:
        if master.hierarchy.level == level:
            return master
        master = master.master
    return None


def _get_pastor(user):
    return _get_master_tree_by_level(user, 2)


def _get_bishop(user):
    return _get_master_tree_by_level(user, 4)


def _get_sotnik(user):
    return _get_pastor(user)


def fullname(user):
    return ' '.join(map(lambda name: name.strip(), (user.last_name, user.first_name, user.middle_name)))


def update_profiles_archive_info(apps, schema_editor):
    Profile = apps.get_model("summit", "SummitAnket")

    for p in Profile.objects.all():
        p.first_name = p.user.first_name
        p.last_name = p.user.last_name
        p.middle_name = p.user.middle_name
        p.search_name = p.user.search_name
        p.city = p.user.city
        p.country = p.user.country
        p.spiritual_level = p.user.spiritual_level

        pastor = _get_pastor(p.user)
        p.pastor = fullname(pastor) if pastor else ''
        p.pastor_fk = pastor

        bishop = _get_bishop(p.user)
        p.bishop = fullname(bishop) if bishop else ''
        p.bishop_fk = bishop

        sotnik = _get_sotnik(p.user)
        p.sotnik = fullname(sotnik) if sotnik else ''
        p.sotnik_fk = sotnik

        master = p.user.master
        p.responsible = fullname(master) if master else ''
        p.master = master

        hierarchy = p.user.hierarchy
        p.hierarchy = hierarchy
        p.hierarchy_title = hierarchy.title if hierarchy else ''

        p.divisions_title = ', '.join(p.user.divisions.values_list('title', flat=True))
        p.department = ', '.join(p.user.departments.values_list('title', flat=True))
        p.save()


class Migration(migrations.Migration):
    dependencies = [
        ('summit', '0043_auto_20170505_1046'),
    ]

    operations = [
        migrations.RunPython(update_profiles_archive_info, lambda a, s: 0),
    ]
