# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0039_auto_20170428_1246'),
        ('summit', '0045_merge_20170515_1903'),
    ]

    operations = [
    ]
