# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0046_auto_20170516_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitvisitorlocation',
            name='type',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='ticket_status',
            field=models.CharField(choices=[('none', 'Without ticket.'), ('download', 'Ticket is created.'), ('print', 'Ticket is printed')], default='none', max_length=20, verbose_name='Ticket status'),
        ),
    ]
