# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0047_auto_20170517_1524'),
        ('summit', '0039_auto_20170517_1456'),
    ]

    operations = [
    ]
