# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0055_auto_20170614_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnketPasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Дата и время прохода')),
                ('anket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_count', to='summit.SummitAnket', verbose_name='Anket')),
            ],
        ),
        migrations.AlterField(
            model_name='anketstatus',
            name='reg_code_requested_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата ввода регистрационного кода'),
        ),
    ]
