# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0062_auto_20170621_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summitanket',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='department',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, verbose_name='Titles of departments'),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, verbose_name='Fisrt name'),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='middle_name',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Visitor'), (20, 'Consultant'), (30, 'Supervisor')], db_index=True, default=10, verbose_name='Summit Role'),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='search_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Field for search by name'),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='spiritual_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Renegade'), (1, 'Baby'), (2, 'Junior'), (3, 'Father')], db_index=True, default=1, verbose_name='Spiritual Level'),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summit_profiles', to='account.CustomUser'),
        ),
    ]
