# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 17:45
from __future__ import unicode_literals

from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0064_summitanket_master_path'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.RunSQL("CREATE INDEX summit_summitanket_54652b36 ON summit_summitanket USING GIN (master_path);")
    ]
