# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0065_auto_20170721_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summit',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='summits', to='summit.SummitType'),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='summit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ankets', to='summit.Summit', verbose_name='Саммит'),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='ticket_status',
            field=models.CharField(choices=[('none', 'Без билета.'), ('download', 'Билет загружен.'), ('print', 'Билет напечатан.'), ('given', 'Билет выдан.')], default='none', max_length=20, verbose_name='Ticket status'),
        ),
        migrations.AlterField(
            model_name='summitanket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summit_profiles', to='account.CustomUser'),
        ),
        migrations.AlterField(
            model_name='summitattend',
            name='anket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attends', to='summit.SummitAnket', verbose_name='Anket'),
        ),
    ]
