# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zmail', '0001_initial'),
        ('summit', '0066_auto_20171210_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketemail',
            name='zmail_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_emails', to='zmail.ZMailTemplate', verbose_name='Mail template'),
        ),
        migrations.AddField(
            model_name='summit',
            name='zmail_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summits', to='zmail.ZMailTemplate', verbose_name='Mail template'),
        ),
    ]
