# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0067_auto_20171218_1605'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE summit_summit DROP COLUMN IF EXISTS mail_template_id;")
    ]
