# Generated by Django 2.0.1 on 2018-02-01 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_district'),
        ('summit', '0068_delete_mail_template_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitanket',
            name='is_dead',
            field=models.BooleanField(default=False, verbose_name='Is Dead'),
        ),
        migrations.AddField(
            model_name='summitanket',
            name='is_stable',
            field=models.BooleanField(default=True, verbose_name='Is Stable'),
        ),
        migrations.AddField(
            model_name='summitanket',
            name='locality',
            field=models.ForeignKey(blank=True, help_text='City/village/etc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='location.City', verbose_name='Locality'),
        ),
        migrations.AlterField(
            model_name='summituserconsultant',
            name='consultant',
            field=models.ForeignKey(limit_choices_to={'role__gte': 20}, on_delete=django.db.models.deletion.CASCADE, related_name='consultees', to='summit.SummitAnket', verbose_name='Consultant'),
        ),
    ]
