# Generated by Django 2.0.2 on 2018-02-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0071_auto_20180226_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrampayment',
            name='liqpay_payment_token',
        ),
        migrations.AddField(
            model_name='telegrampayment',
            name='liqpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID проплаченного счета в системе LiqPay'),
        ),
        migrations.AlterField(
            model_name='telegrampayment',
            name='liqpay_payment_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID созданого в системе LiqPay'),
        ),
    ]
