# Generated by Django 2.0.2 on 2018-03-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0072_auto_20180228_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrampayment',
            name='chat_id',
            field=models.IntegerField(verbose_name='ID Telegram чата'),
        ),
        migrations.AlterField(
            model_name='telegrampayment',
            name='liqpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID оплаченного счета в системе LiqPay'),
        ),
        migrations.AlterField(
            model_name='telegrampayment',
            name='liqpay_payment_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID выставленного счета в системе LiqPay'),
        ),
        migrations.AlterField(
            model_name='telegrampayment',
            name='secret',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код регистрации'),
        ),
    ]
