# Generated by Django 2.0.6 on 2018-06-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0074_telegrampayment_err_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='summit',
            name='one_entry',
            field=models.BooleanField(default=False, verbose_name='Only one entry'),
        ),
    ]
