# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import event.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('day', event.models.DayOfTheWeekField(choices=[('1', '\u041f\u043e\u043d\u0435\u0434\u0435\u043b\u044c\u043d\u0438\u043a'), ('2', '\u0412\u0442\u043e\u0440\u043d\u0438\u043a'), ('3', '\u0421\u0440\u0435\u0434\u0430'), ('4', '\u0427\u0435\u0442\u0432\u0435\u0440\u0433'), ('5', '\u041f\u044f\u0442\u043d\u0438\u0446\u0430'), ('6', '\u0421\u0443\u0431\u0431\u043e\u0442\u0430'), ('7', '\u0412\u043e\u0441\u043a\u0440\u0435\u0441\u0435\u043d\u044c\u0435')], max_length=1, null=True)),
                ('active', models.BooleanField(default=True)),
                ('cyclic', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name_plural': '\u0421\u043e\u0431\u044b\u0442\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='event.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='account.CustomUser')),
            ],
            options={
                'verbose_name_plural': '\u0423\u0447\u0430\u0441\u0442\u0438\u044f',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='events', through='event.Participation', to='account.CustomUser'),
        ),
    ]
