# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
