# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-01 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20160601_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.CharField(default='', max_length=5),
        ),
    ]
