# Generated by Django 2.0.1 on 2018-01-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_auto_20171210_1447'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='OldCity',
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='OldCountry',
        ),
        migrations.RenameModel(
            old_name='Region',
            new_name='OldRegion',
        ),
        migrations.AlterModelTable(
            name='oldcity',
            table='location_city',
        ),
        migrations.AlterModelTable(
            name='oldcountry',
            table='location_country',
        ),
        migrations.AlterModelTable(
            name='oldregion',
            table='location_region',
        ),
    ]
