# Generated by Django 2.0.1 on 2018-01-25 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_auto_20180125_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Name')),
                ('okrug', models.CharField(blank=True, max_length=128, verbose_name='Okrug')),
                ('autocod', models.CharField(blank=True, max_length=128, verbose_name='Auto code')),
                ('capital', models.PositiveIntegerField(default=0, verbose_name='Capital')),
                ('english', models.CharField(blank=True, max_length=64, verbose_name='English name')),
                ('iso', models.CharField(blank=True, max_length=3, verbose_name='ISO')),
            ],
            options={
                'db_table': 'geo_area',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Name')),
                ('telcod', models.CharField(blank=True, db_index=True, max_length=48, verbose_name='Tel code')),
                ('english', models.CharField(blank=True, max_length=64, verbose_name='English name')),
                ('rajon', models.PositiveIntegerField(default=0, verbose_name='Rajon')),
                ('sound', models.CharField(blank=True, db_index=True, max_length=4, verbose_name='Sound')),
                ('level', models.SmallIntegerField(choices=[(0, '---------'), (1, 'Столица Округа'), (2, 'Крупный город'), (3, 'Небольшой населенный пункт')], default=0, verbose_name='Level')),
                ('iso', models.CharField(blank=True, max_length=3, verbose_name='ISO')),
                ('vid', models.SmallIntegerField(verbose_name='Level')),
                ('post', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Post')),
                ('geonameid', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Geo name id')),
                ('timezone', models.FloatField(blank=True, null=True, verbose_name='Timezone')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='location.Area', verbose_name='Area')),
            ],
            options={
                'db_table': 'geo_city',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('fullname', models.CharField(blank=True, max_length=256, verbose_name='Full name')),
                ('english', models.CharField(blank=True, max_length=64, verbose_name='English name')),
                ('country_code3', models.CharField(blank=True, max_length=3, verbose_name='Country code 3')),
                ('iso', models.CharField(blank=True, max_length=3, verbose_name='ISO')),
                ('telcod', models.CharField(blank=True, max_length=4, verbose_name='Tel code')),
                ('location', models.CharField(default='', max_length=20, verbose_name='Location')),
                ('capital', models.PositiveIntegerField(default=0, verbose_name='Capital')),
                ('mcc', models.PositiveIntegerField(default=0, verbose_name='Код страны телефонных операторов')),
                ('lang', models.CharField(blank=True, max_length=128, verbose_name='Name')),
            ],
            options={
                'db_table': 'geo_country',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='location.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='area',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='location.Country', verbose_name='Country'),
        ),
    ]
