# Generated by Django 2.0.1 on 2018-01-27 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_auto_20180125_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('area_id', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Area')),
                ('capital', models.PositiveIntegerField(default=0, verbose_name='Capital')),
                ('english', models.CharField(blank=True, max_length=64, verbose_name='English name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='location.Country', verbose_name='Country')),
            ],
            options={
                'db_table': 'geo_rajon',
            },
        ),
    ]
