# Generated by Django 2.0.6 on 2018-07-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='vid',
            field=models.SmallIntegerField(choices=[(0, '---------'), (1, 'Город'), (2, 'Поселок'), (3, 'Село'), (4, 'Деревня'), (5, 'Станица'), (6, 'Хутор')], default=0, verbose_name='Level'),
        ),
    ]
