# Generated by Django 2.0.5 on 2018-06-06 07:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0044_added_sex_field'),
        ('location', '0010_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(editable=False, max_length=25, verbose_name='Status')),
                ('note', models.TextField(verbose_name='Note')),
                ('closed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Closed at')),
                ('reason', models.CharField(choices=[('create', 'Create'), ('update', 'Update')], editable=False, max_length=25, verbose_name='Reason')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created at')),
                ('manager', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposal_histories', to='account.CustomUser', verbose_name='Manager')),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_histories', to='account.CustomUser', verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last name')),
                ('sex', models.CharField(default='unknown', max_length=7, verbose_name='Sex')),
                ('born_date', models.DateField(blank=True, null=True, verbose_name='Born date')),
                ('email', models.CharField(blank=True, max_length=254, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=23, verbose_name='Phone number')),
                ('type', models.CharField(default='other', max_length=25, verbose_name='Type')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('reopen', 'Reopen'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='open', max_length=25, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed at')),
                ('note', models.TextField(verbose_name='Note')),
                ('locality', models.ForeignKey(blank=True, help_text='City/village/etc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='location.City', verbose_name='Locality')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager_proposals', to='account.CustomUser', verbose_name='Manager')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='account.CustomUser', verbose_name='User')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='history',
            name='proposal',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='proposal.Proposal', verbose_name='Proposal'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.CustomUser', verbose_name='User'),
        ),
    ]
