# Generated by Django 2.0.6 on 2018-06-11 09:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='age_group',
            field=models.CharField(blank=True, max_length=255, verbose_name='Age group'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='directions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='proposal',
            name='gender_group',
            field=models.CharField(blank=True, max_length=255, verbose_name='Gender group'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='geo_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='GEO location'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='leader_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Leader fio'),
        ),
    ]
