# Generated by Django 2.0.6 on 2018-06-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_auto_20180611_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='country',
            field=models.CharField(blank=True, max_length=120, verbose_name='Country'),
        ),
    ]
