# Generated by Django 2.0.6 on 2018-07-05 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0005_auto_20180703_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventproposal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.CustomUser'),
        ),
    ]
