# Generated by Django 2.0.8 on 2018-09-05 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0006_auto_20180705_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhistory',
            name='profile',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='summit.SummitAnket', verbose_name='Event profile'),
        ),
        migrations.AlterField(
            model_name='eventproposal',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='summit.SummitAnket', verbose_name='Event profile'),
        ),
    ]
