# Generated by Django 2.0.2 on 2018-02-13 14:16

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('position', models.PositiveSmallIntegerField(verbose_name='Position')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Manual',
                'verbose_name_plural': 'Manuals',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='ManualCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('position', models.PositiveSmallIntegerField(verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('position',),
            },
        ),
        migrations.AddField(
            model_name='manual',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manuals', to='help.ManualCategory', verbose_name='Manual Category'),
        ),
    ]
