# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-29 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('common', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ColumnType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('verbose_title', models.CharField(blank=True, max_length=100, null=True)),
                ('ordering_title', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columnTypes', to='navigation.Category')),
            ],
            options={
                'verbose_name_plural': '\u041a\u043e\u043b\u043e\u043d\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u041d\u0430\u0432\u0438\u0433\u0430\u0446\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columnTypes', models.ManyToManyField(blank=True, related_name='tables', through='navigation.Column', to='navigation.ColumnType')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='account.CustomUser')),
            ],
        ),
        migrations.AddField(
            model_name='column',
            name='columnType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='navigation.ColumnType'),
        ),
        migrations.AddField(
            model_name='column',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='navigation.Table'),
        ),
    ]
