# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_user_columns'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='column',
            unique_together=set([('table', 'columnType')]),
        ),
    ]
