# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 13:22
from __future__ import unicode_literals

from django.db import migrations


def department_to_departments_column(apps, schema_editor):
    CustomUsers_columns = apps.get_model("navigation", "ColumnType")
    Category = apps.get_model("navigation", "Category")

    ch = Category.objects.filter(title='Общая информация')
    if ch.exists():
        CustomUsers_columns.objects.filter(title='department', category=ch.get()).update(title='departments')


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_group_columns_v2'),
    ]

    operations = [
        migrations.RunPython(department_to_departments_column)
    ]
