# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 12:29
from __future__ import unicode_literals

from django.db import migrations


def add_summit_column_ticket_status(apps, schema_editor):
    Category = apps.get_model("navigation", "Category")
    ColumnType = apps.get_model("navigation", "ColumnType")

    category, _ = Category.objects.get_or_create(title='summit')
    c = {'title': 'ticket_status', 'verb': 'Статус билета', 'order': 'ticket_status'}
    ColumnType.objects.create(
        title=c['title'],
        category=category,
        verbose_title=c['verb'],
        ordering_title=c['order'],
        number=22,
        active=True,
        editable=True)


def delete_summit_column_ticket_status(apps, schema_editor):
    ColumnType = apps.get_model("navigation", "ColumnType")
    ColumnType.objects.filter(title='ticket_status').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('navigation', '0007_auto_20170505_1558'),
    ]

    operations = [
        migrations.RunPython(add_summit_column_ticket_status, delete_summit_column_ticket_status)
    ]
