# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 15:12
from __future__ import unicode_literals

from django.db import migrations


def create_event_columns(apps, schema_editor):
    Event_columns = apps.get_model("navigation", "ColumnType")
    Category = apps.get_model("navigation", "Category")

    event = Category.objects.create(title='event', common=True)

    Event_columns.objects.bulk_create([
        Event_columns(title='date', verbose_title='Дата создания', ordering_title='date', number=1, active=True,
                      editable=False, category_id=event.id),
        Event_columns(title='home_group', verbose_title='Домашняя группа', ordering_title='home_group__title', number=2,
                      active=True, editable=True, category_id=event.id),
        Event_columns(title='owner', verbose_title='Владелец отчета', ordering_title='owner__last_name',
                      number=3, active=True, editable=True, category_id=event.id),
        Event_columns(title='phone_number', verbose_title='Телефонный номер', ordering_title='phone_number',
                      number=4, active=True, editable=True, category_id=event.id),
        Event_columns(title='type', verbose_title='Тип отчета', ordering_title='type__code', number=5, active=True,
                      editable=True, category_id=event.id),
        Event_columns(title='visitors_attended', verbose_title='Присутствовали', ordering_title='visitors_attended',
                      number=6, active=True, editable=True, category_id=event.id),
        Event_columns(title='visitors_absent', verbose_title='Отсутствовали', ordering_title='visitors_absent',
                      number=7, active=True, editable=True, category_id=event.id),
        Event_columns(title='total_sum', verbose_title='Сумма пожертвований', ordering_title='total_sum', number=8,
                      active=True, editable=True, category_id=event.id),
    ])


def delete_event_columns(apps, schema_editor):
    Event_columns = apps.get_model("navigation", "ColumnType")
    Category = apps.get_model("navigation", "Category")

    Event_columns.objects.filter(category__title='event').delete()
    Category.objects.filter(title="event").delete()


class Migration(migrations.Migration):
    dependencies = [
        ('navigation', '0007_merge_20170412_1631'),
    ]

    operations = [
        migrations.RunPython(create_event_columns, delete_event_columns),
    ]
