# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 15:12
from __future__ import unicode_literals

from django.db import migrations


def create_meeting_columns(apps, schema_editor):
    Meeting_columns = apps.get_model("navigation", "ColumnType")
    Category = apps.get_model("navigation", "Category")

    meetings = Category.objects.create(title='meetings', common=True)

    Meeting_columns.objects.bulk_create([
        Meeting_columns(title='date', verbose_title='Дата создания', ordering_title='date', number=1, active=True,
                        editable=False, category_id=meetings.id),
        Meeting_columns(title='home_group', verbose_title='Домашняя группа', ordering_title='home_group__title',
                        number=2, active=True, editable=True, category_id=meetings.id),
        Meeting_columns(title='owner', verbose_title='Владелец отчета', ordering_title='owner__last_name',
                        number=3, active=True, editable=True, category_id=meetings.id),
        Meeting_columns(title='phone_number', verbose_title='Телефонный номер', ordering_title='phone_number',
                        number=4, active=True, editable=True, category_id=meetings.id),
        Meeting_columns(title='type', verbose_title='Тип отчета', ordering_title='type__code', number=5, active=True,
                        editable=True, category_id=meetings.id),
        Meeting_columns(title='visitors_attended', verbose_title='Присутствовали', ordering_title='visitors_attended',
                        number=6, active=True, editable=True, category_id=meetings.id),
        Meeting_columns(title='visitors_absent', verbose_title='Отсутствовали', ordering_title='visitors_absent',
                        number=7, active=True, editable=True, category_id=meetings.id),
        Meeting_columns(title='total_sum', verbose_title='Сумма пожертвований', ordering_title='total_sum', number=8,
                        active=True, editable=True, category_id=meetings.id),
    ])


def create_meeting_attends_columns(apps, schema_editor):
    Attends_columns = apps.get_model("navigation", "ColumnType")
    Category = apps.get_model("navigation", 'Category')

    attends = Category.objects.create(title='attends', common=True)

    Attends_columns.objects.bulk_create([
        Attends_columns(title='attended', verbose_title='Присутствие', ordering_title='attended',
                        number=1, active=True, editable=True, category_id=attends.id),
        Attends_columns(title='user', verbose_title='ФИО', ordering_title='user__last_name',
                        number=2, active=True, editable=False, category_id=attends.id),
        Attends_columns(title='spiritual_level', verbose_title='Духовный Уровень', ordering_title='user__last_name',
                        number=3, active=True, editable=True, category_id=attends.id),
        Attends_columns(title='phone_number', verbose_title='Телефонный номер', ordering_title='user__phone_number',
                        number=4, active=True, editable=True, category_id=attends.id),
        Attends_columns(title='note', verbose_title='Комментарий', ordering_title='note',
                        number=5, active=True, editable=True, category_id=attends.id),
    ])


def delete_meeting_columns(apps, schema_editor):
    Meeting_columns = apps.get_model("navigation", "ColumnType")
    Category = apps.get_model("navigation", "Category")

    Meeting_columns.objects.filter(category__title='meetings').delete()
    Category.objects.filter(title="meetings").delete()


def delete_meeting_attends_columns(apps, schema_editor):
    Meeting_columns = apps.get_model("navigation", "ColumnType")
    Category = apps.get_model("navigation", "Category")

    Meeting_columns.objects.filter(category__title='attends').delete()
    Category.objects.filter(title='attends').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('navigation', '0007_merge_20170412_1631'),
    ]

    operations = [
        migrations.RunPython(create_meeting_columns, delete_meeting_columns),
        migrations.RunPython(create_meeting_attends_columns, delete_meeting_attends_columns)
    ]
