# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 11:22
from __future__ import unicode_literals

from django.db import migrations


def update_meeting_date_column(apps, schema_editor):
    Meeting_columns = apps.get_model('navigation', 'ColumnType')

    meeting_date_column = Meeting_columns.objects.filter(category__title='meetings').filter(title='date')
    meeting_date_column.update(number=9, editable=True)


def create_meeting_id_column(apps, schema_editor):
    Meeting_columns = apps.get_model('navigation', 'ColumnType')
    Category = apps.get_model('navigation', 'Category')

    meeting = Category.objects.get(title='meetings')

    Meeting_columns.objects.bulk_create([
        Meeting_columns(title='id', verbose_title='№', ordering_title='id',
                        number=1, active=True, editable=False, category_id=meeting.id)
    ])


def delete_meeting_id_column(apps, schema_editor):
    Meeting_columns = apps.get_model('navigation', 'ColumnType')

    Meeting_columns.objects.filter(category__title='meetings').filter(title='id').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0008_create_meeting_columns'),
    ]

    operations = [
        migrations.RunPython(update_meeting_date_column),
        migrations.RunPython(create_meeting_id_column, delete_meeting_id_column)
    ]
