# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 11:28
from __future__ import unicode_literals

from django.db import migrations


def create_church_report_columns(apps, schema_editor):
    Church_report_columns = apps.get_model("navigation", "ColumnType")
    Category = apps.get_model("navigation", "Category")

    church_report = Category.objects.create(title='church_report', common=True)

    Church_report_columns.objects.bulk_create([
        Church_report_columns(title='id', verbose_title='№', ordering_title='id', number=1, active=True,
                              editable=False, category_id=church_report.id),
        Church_report_columns(title='date', verbose_title='Дата создания', ordering_title='date', number=2,
                              active=True, editable=True, category_id=church_report.id),
        Church_report_columns(title='church', verbose_title='Церковь', ordering_title='church__title',
                              number=3, active=True, editable=True, category_id=church_report.id),
        Church_report_columns(title='pastor', verbose_title='Пастор Церкви', ordering_title='pastor__last_name',
                              number=4, active=True, editable=True, category_id=church_report.id),
        Church_report_columns(title='total_peoples', verbose_title='Людей на собрание',
                              ordering_title='total_peoples', number=5, active=True, editable=True,
                              category_id=church_report.id),
        Church_report_columns(title='total_new_peoples', verbose_title='Новых людей',
                              ordering_title='total_new_peoples', number=6, active=True, editable=True,
                              category_id=church_report.id),
        Church_report_columns(title='total_repentance', verbose_title='Покаяний',
                              ordering_title='total_repentance',
                              number=7, active=True, editable=True, category_id=church_report.id),
        Church_report_columns(title='total_tithe', verbose_title='Десятины', ordering_title='total_tithe',
                              number=8, active=True, editable=True, category_id=church_report.id),
        Church_report_columns(title='total_donations', verbose_title='Пожертвования',
                              ordering_title='total_donations', number=9,
                              active=True, editable=True, category_id=church_report.id),
        Church_report_columns(title='total_pastor_tithe', verbose_title='15% к перечислению',
                              ordering_title='total_pastor_tithe', number=10,
                              active=True, editable=True, category_id=church_report.id),
        Church_report_columns(title='total_pastor_tithe', verbose_title='Десятина пастора',
                              ordering_title='total_pastor_tithe', number=10,
                              active=True, editable=True, category_id=church_report.id),
    ])


def delete_church_reports_columns(apps, schema_editor):
    Church_reports_columns = apps.get_model("navigation", "ColumnType")
    Category = apps.get_model("navigation", "Category")

    Church_reports_columns.objects.filter(category__title='church_reports').delete()
    Category.objects.filter(title="church_reports").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0011_merge_20170519_0912'),
    ]

    operations = [
        migrations.RunPython(create_church_report_columns, delete_church_reports_columns),
    ]
