# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 16:11
from __future__ import unicode_literals

from django.db import migrations


def create_summit_ankets_e_ticket_column(apps, schema_editor):
    Summit_anket_columns = apps.get_model("navigation", "ColumnType")
    Category = apps.get_model("navigation", "Category")

    e_ticket = Category.objects.get(title='summit')

    Summit_anket_columns.objects.bulk_create([
        Summit_anket_columns(title='e_ticket', verbose_title='Электронный билет',
                             ordering_title='status__reg_code_requested', number=23, active=True,
                             editable=True, category_id=e_ticket.id),
    ])


def delete_summit_ankets_e_ticket_column(apps, schema_editor):
    ColumnType = apps.get_model("navigation", "ColumnType")
    ColumnType.objects.filter(category__title='summit').filter(title='id').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0012_auto_20170606_1128'),
    ]

    operations = [
        migrations.RunPython(create_summit_ankets_e_ticket_column, delete_summit_ankets_e_ticket_column)
    ]
