# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0016_auto_20170731_1608'),
    ]

    operations = [
    ]
