# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 10:31
from __future__ import unicode_literals

from django.db import migrations


def create_church_report_columns(apps, schema_editor):
    Church_report_columns = apps.get_model("navigation", "ColumnType")
    Category = apps.get_model("navigation", "Category")

    church_report = Category.objects.get(title='church_report')

    Church_report_columns.objects.bulk_create([
        Church_report_columns(title='transfer_payments', verbose_title='15% к перечислению',
                              ordering_title='transfer_payments', number=11, active=True,
                              editable=True, category_id=church_report.id),
        Church_report_columns(title='currency_donations', verbose_title='Пожертвования в другой валюте',
                              ordering_title='currency_donations', number=12, active=True, editable=True,
                              category_id=church_report.id),
        Church_report_columns(title='value', verbose_title='Сумма', ordering_title='value', number=13,
                              active=True, editable=True, category_id=church_report.id),
        Church_report_columns(title='action', verbose_title='Действие', ordering_title='payment_status',
                              number=14, active=True, editable=True, category_id=church_report.id),
    ])


def delete_church_report_columns(apps, schema_editor):
    Church_reports_columns = apps.get_model("navigation", "ColumnType")
    Category = apps.get_model("navigation", "Category")

    Church_reports_columns.objects.filter(category__title='church_report').filter(
        title__in=['currency_donations', 'transfer_payments', 'sum', 'action']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0017_auto_20170804_1712'),
    ]

    operations = [
        migrations.RunPython(create_church_report_columns, delete_church_report_columns),
    ]
