# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 12:59
from __future__ import unicode_literals

from django.db import migrations


def update_payment_columns_ordering_title(apps, schema_editor):
    Payment_columns = apps.get_model('navigation', 'ColumnType')

    church_report_column = Payment_columns.objects.filter(category__title='payment').filter(
        title='purpose_manager_fio')
    church_report_column.update(verbose_title='Менеджер')

    church_report_column = Payment_columns.objects.filter(category__title='payment').filter(
        title='manager')
    church_report_column.update(verbose_title='Супеврайзер')


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0021_auto_20170901_1646'),
    ]

    operations = [
        migrations.RunPython(update_payment_columns_ordering_title)
    ]
