# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 15:43
from __future__ import unicode_literals

from django.db import migrations


def update_payment_columns_ordering_title(apps, schema_editor):
    Payment_columns = apps.get_model('navigation', 'ColumnType')

    payment_columns = Payment_columns.objects.filter(category__title='payment').filter(
        title='purpose_manager_fio')
    payment_columns.update(verbose_title='Супервайзер')

    payment_columns = Payment_columns.objects.filter(category__title='payment').filter(
        title='manager')
    payment_columns.update(verbose_title='Менеджер')


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0021_auto_20170901_1646'),
    ]

    operations = [
        migrations.RunPython(update_payment_columns_ordering_title)
    ]
   