# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 14:49
from __future__ import unicode_literals

from django.db import migrations


def create_deal_type_column(apps, schema_editor):
    Deal_columns = apps.get_model('navigation', 'ColumnType')
    Category = apps.get_model("navigation", "Category")

    deal_columns = Category.objects.get(title='deal')

    Deal_columns.objects.bulk_create([
        Deal_columns(title='type', verbose_title='Тип сделки',
                     ordering_title='type',
                     number=5, active=True, editable=True, category_id=deal_columns.id)
    ])


def create_payment_type_of_deal_column(apps, schema_editor):
    Payment_columns = apps.get_model('navigation', 'ColumnType')
    Category = apps.get_model('navigation', 'Category')

    payment_columns = Category.objects.get(title='payment')

    Payment_columns.objects.bulk_create([
        Payment_columns(title='purpose_type', verbose_title='Тип сделки',
                        ordering_title='deals__type',
                        number=9, active=True, editable=True, category_id=payment_columns.id)
    ])


def delete_deal_type_column(apps, schema_editor):
    Deal_columns = apps.get_model("navigation", "ColumnType")

    Deal_columns.objects.filter(category__title='deal').filter(title='type').delete()


def delete_payment_type_of_deal_column(apps, schema_editor):
    Payment_columns = apps.get_model("navigation", 'ColumnType')

    Payment_columns.objects.filter(category__title='payment').filter(title='purpose_type').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('navigation', '0023_auto_20170911_1256'),
    ]

    operations = [
        migrations.RunPython(create_deal_type_column, delete_deal_type_column,
                             create_payment_type_of_deal_column, delete_payment_type_of_deal_column)
    ]
