# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 16:55
from __future__ import unicode_literals

from django.db import migrations


def create_sum_pay_column(apps, schema_editor):
    Partnership_summary_columns = apps.get_model("navigation", "ColumnType")
    Category = apps.get_model("navigation", "Category")

    partnership_summary = Category.objects.get(title='partnership_summary')

    Partnership_summary_columns.objects.bulk_create([
        Partnership_summary_columns(title='sum_pay_tithe', verbose_title='Сумма дестин',
                                    ordering_title='sum_pay_tithe',
                                    number=10, active=True, editable=True, category_id=partnership_summary.id)
    ])

    sum_pay_column = Partnership_summary_columns.objects.filter(category__title='partnership_summary').filter(
        title='sum_pay')
    sum_pay_column.update(verbose_title='Сумма партнерских')


def delete_sum_pay_tithe_column(apps, schema_editor):
    Partnership_summary_columns = apps.get_model("navigation", "ColumnType")

    Partnership_summary_columns.objects.filter(category__title='partnership_summary').filter(
        title='sum_pay_tithe').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0025_auto_20170914_1430'),
    ]

    operations = [
        migrations.RunPython(create_sum_pay_column, delete_sum_pay_tithe_column)
    ]
