# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 10:41
from __future__ import unicode_literals

from django.db import migrations


def rename_fileds(apps, schema_editor):
    ColumnType = apps.get_model("navigation", "ColumnType")

    ColumnType.objects.filter(
        ordering_title='responsible__user__last_name').update(
        ordering_title='responsible__last_name')
    ColumnType.objects.filter(
        ordering_title='deals__partnership__responsible__user__last_name').update(
        ordering_title='deals__partnership__responsible__last_name')


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0028_auto_20170922_1839'),
        ('partnership', '0040_rename_uresponsible_to_responsible')
    ]

    operations = [
        migrations.RunPython(rename_fileds),
    ]
