# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 12:25
from __future__ import unicode_literals

from django.db import migrations


def rename_fileds(apps, schema_editor):
    ColumnType = apps.get_model("navigation", "ColumnType")

    ColumnType.objects.filter(
        ordering_title='deals__partnership__responsible__last_name').update(
        ordering_title='deals__responsible__last_name')


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0029_rename_responsible_columns'),
    ]

    operations = [
        migrations.RunPython(rename_fileds),
    ]
