# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 15:48
from __future__ import unicode_literals

from django.db import migrations


def create_partner_group_column(apps, schema_editor):
    ColumnType = apps.get_model("navigation", "ColumnType")
    Category = apps.get_model("navigation", "Category")

    category = Category.objects.get(title='partnership')

    ColumnType.objects.create(
        title='group', verbose_title='Тег',
        ordering_title='group__title',
        number=11, active=True, editable=True, category=category)


def delete_partner_group_column(apps, schema_editor):
    ColumnType = apps.get_model("navigation", "ColumnType")

    ColumnType.objects.filter(category__title='partnership', title='group').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('navigation', '0030_rename_column'),
    ]

    operations = [
        migrations.RunPython(create_partner_group_column, delete_partner_group_column)
    ]
