# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0031_create_partner_group_column'),
    ]

    operations = [
    ]
