# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 17:45
from __future__ import unicode_literals

from django.db import migrations


def create_has_email_column(apps, schema_editor):
    ColumnType = apps.get_model("navigation", "ColumnType")
    Category = apps.get_model("navigation", "Category")

    category = Category.objects.get(title='summit')

    ColumnType.objects.create(
        title='has_email', verbose_title='Email отправлен',
        ordering_title='has_email',
        number=12, active=True, editable=True, category=category)


def delete_has_email_column(apps, schema_editor):
    ColumnType = apps.get_model("navigation", "ColumnType")

    ColumnType.objects.filter(category__title='summit', title='has_email').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0032_auto_20171031_1511'),
    ]

    operations = [
        migrations.RunPython(create_has_email_column, delete_has_email_column)
    ]
