# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 15:42
from __future__ import unicode_literals

from django.db import migrations


def create_done_column(apps, schema_editor):
    ColumnType = apps.get_model("navigation", "ColumnType")
    Category = apps.get_model("navigation", "Category")

    category = Category.objects.get(title='deal')

    ColumnType.objects.create(
        title='done', verbose_title='Закрыта',
        ordering_title='done',
        number=13, active=True, editable=True, category=category)


def delete_done_column(apps, schema_editor):
    ColumnType = apps.get_model("navigation", "ColumnType")

    ColumnType.objects.filter(category__title='deal', title='done').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0033_add_has_email_column_for_summit_table'),
    ]

    operations = [
        migrations.RunPython(create_done_column, delete_done_column)
    ]
