# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-05 13:34
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20170105_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12, verbose_name='Rate'),
        ),
    ]
