# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20170105_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='effective_sum',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True, verbose_name='Effective sum'),
        ),
    ]
