# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20170110_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sent_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Sent date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created'),
        ),
    ]
