# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 15:53
from __future__ import unicode_literals

from django.db import migrations


def write_sent_date(apps, schema_editor):
    Payment = apps.get_model("payment", "Payment")

    for payment in Payment.objects.all():
        payment.sent_date = payment.created_at
        payment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20170203_1753'),
    ]

    operations = [
        migrations.RunPython(write_sent_date)
    ]
