# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20170216_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='operation',
            field=models.CharField(choices=[('*', 'Multiplication'), ('/', 'Division')], default='*', max_length=1, verbose_name='Operation'),
        ),
    ]
