# Generated by Django 2.0.2 on 2018-02-05 15:06

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_payment_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='sum',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=12, verbose_name='Sum'),
        ),
    ]
