# Generated by Django 2.0.2 on 2018-02-06 15:19

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20180205_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Sum'),
        ),
    ]
