# Generated by Django 2.0.2 on 2018-03-04 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20180206_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('summitanket', 'partnership', 'deal', 'churchreport')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
