# Generated by Django 2.0.2 on 2018-03-06 14:34

import common.date_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20180304_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='sent_date',
            field=models.DateField(default=common.date_utils.today, verbose_name='Sent date'),
        ),
    ]
