# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('user', models.ManyToManyField(related_name='statuses', to='account.CustomUser')),
            ],
        ),
    ]
